package com.jh.cltApp.mapping;

import com.jh.cltApp.entity.CltMediaSource;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface ICltMediaSourceMapper {

    List<CltMediaSource> findCltMediaSourceListByItemId(Integer itemId);

    void deleteMediaSourceByTaskId(Integer taskId);

    void deleteMediaSourceByItemId(Integer itemId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clt_media_source
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer mediaId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clt_media_source
     *
     * @mbggenerated
     */
    int insert(CltMediaSource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clt_media_source
     *
     * @mbggenerated
     */
    int insertSelective(CltMediaSource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clt_media_source
     *
     * @mbggenerated
     */
    CltMediaSource selectByPrimaryKey(Integer mediaId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clt_media_source
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CltMediaSource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clt_media_source
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CltMediaSource record);
}