package com.jh.cltApp.mapping;

import com.jh.cltApp.entity.CltTaskUser;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface ICltTaskUserMapper {

    List<CltTaskUser> findCltTaskUserList(CltTaskUser cltTaskUser);

    void deleteCltTaskUserByTaskId(Integer taskId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clt_task_user
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clt_task_user
     *
     * @mbggenerated
     */
    int insert(CltTaskUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clt_task_user
     *
     * @mbggenerated
     */
    int insertSelective(CltTaskUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clt_task_user
     *
     * @mbggenerated
     */
    CltTaskUser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clt_task_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CltTaskUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clt_task_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CltTaskUser record);
}