package com.jh.cltApp.mapping;

import com.jh.cltApp.entity.CltTaskItem;
import com.jh.cltApp.vo.CltTaskItemVO;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface ICltTaskItemMapper {

    List<CltTaskItemVO> findTaskItemList(CltTaskItem cltTaskItem);

    List<CltTaskItemVO> findAllTaskItemList(CltTaskItem cltTaskItem);

    CltTaskItemVO findTaskItemByItemId(CltTaskItem cltTaskItem);

    /**
     * 查看自己创建的采集点数据
     * @param
     * @return 
     * @version <1> 2019/4/17 15:24 zhangshen:Created.
     */
    List<CltTaskItemVO> findTaskItemListSelf(CltTaskItem cltTaskItem);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clt_task_item
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer itemId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clt_task_item
     *
     * @mbggenerated
     */
    int insert(CltTaskItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clt_task_item
     *
     * @mbggenerated
     */
    int insertSelective(CltTaskItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clt_task_item
     *
     * @mbggenerated
     */
    CltTaskItem selectByPrimaryKey(Integer itemId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clt_task_item
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CltTaskItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clt_task_item
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CltTaskItem record);

    int createTaskItem(CltTaskItemVO cltTaskItemVO);
}