package com.jh.layer.mapping;

import com.jh.layer.entity.DsGeoStyle;
import com.jh.layer.model.DsGeoStyleParam;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

/**
 * Description: 样式管理Mapper
 * @version <1> 2018/6/19 15:15 zhangshen: Created.
 */
@Mapper
public interface IDsGeoStyleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ds_geo_style
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer styleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ds_geo_style
     *
     * @mbggenerated
     */
    int insert(DsGeoStyle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ds_geo_style
     *
     * @mbggenerated
     */
    int insertSelective(DsGeoStyle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ds_geo_style
     *
     * @mbggenerated
     */
    DsGeoStyle selectByPrimaryKey(Integer styleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ds_geo_style
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(DsGeoStyle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ds_geo_style
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(DsGeoStyle record);

    /**
     * Description: 样式查询列表
     * @param dsGeoStyleParam
     * @return List<DsGeoStyle>
     * @version <1> 2018/6/19 15:45 zhangshen: Created.
     */
    List<DsGeoStyle> findDsGeoStylePageInfo(DsGeoStyleParam dsGeoStyleParam);


}