package com.jh.data.mapping;

import com.jh.data.entity.DsT;
import com.jh.data.model.*;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;
import java.util.Map;

@Mapper
public interface IDsTMapper {
    /**
     * @description: 查询地温明细
     * @param dsTParam 地温明细对象
     * @version <1> 2018-06-07 wl： Created.
     */
    List<DsT> findByPage(DsTParam dsTParam);

    /**
     * @description: 更新地温明细
     * @param dsTParam 地温明细对象
     * @return
     * @version <1> 2018-05-08 wl： Created.
     */
    int updateDsT(DsTParam dsTParam);

    /**
     * @description: 根据id查询详细信息
     * @param id 地温明细主键
     * @return
     * @version<1> 2018-05-08 wl: Created.
     */
    DsT findById(Integer id);

    /**
     * @description: 发布地温明细
     * @param dsTParam 发布人名称  发布人id  发布状态（发布、撤销）
     * @return
     * @version <1> 2018-05-17 wl： Created.
     */
    int publish(DsTParam dsTParam);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ds_t
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ds_t
     *
     * @mbggenerated
     */
    int insert(DsT record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ds_t
     *
     * @mbggenerated
     */
    int insertSelective(DsT record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ds_t
     *
     * @mbggenerated
     */
    DsT selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ds_t
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(DsT record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ds_t
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(DsT record);

    /**
     *查询指定时间类上中下旬的地温均值
     * @param param
     * @return
     * @version <1> 2018-3-21 lxy:Created
     */
    List<TemTrmmTotalDataReturn> findTByTenDays(TtnParam param);


    /**
     * 查询历史时间段上中下旬的地温均值
     * @param param
     * @return
     * @version <1> 2018-3-22 lxy:Created
     */
    List<TenDaysTrmmDataReturn> findHistoryAvgForTTotal(Map<String, Object> param);

    /**
     * 根据区域、作物、精度 查询数据时间列表
     * @param reportCreateParam
     * @return
     * @version<1> 2018-07-18 zhangshen: Created.
     */
    List<DsT> queryDateTimeList(ReportCreateParam reportCreateParam);
}