package com.jh.data.mapping;

import com.jh.data.entity.DsTrmm;
import com.jh.data.model.*;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;
import java.util.Map;

@Mapper
public interface IDsTrmmMapper {

    /**
     * @description: 查询降雨明细
     * @param dsTrmmParam 降雨明细对象
     * @version <1> 2018-06-08 wl： Created.
     */
    List<DsTrmm> findByPage(DsTrmmParam dsTrmmParam);

    /**
     * @description: 更新降雨明细
     * @param dsTrmmParam 降雨明细对象
     * @return
     * @version <1> 2018-06-08 wl： Created.
     */
    int updateDsTrmm(DsTrmmParam dsTrmmParam);

    /**
     * @description: 根据id查询详细信息
     * @param id 降雨明细主键
     * @return
     * @version<1> 2018-06-08 wl: Created.
     */
    DsTrmm findById(Integer id);

    /**
     * @description: 发布降雨明细
     * @param dsTrmmParam 发布人名称  发布人id  发布状态（发布、撤销）
     * @return
     * @version <1> 2018-06-17 wl： Created.
     */
    int publish(DsTrmmParam dsTrmmParam);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ds_trmm
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ds_trmm
     *
     * @mbggenerated
     */
    int insert(DsTrmm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ds_trmm
     *
     * @mbggenerated
     */
    int insertSelective(DsTrmm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ds_trmm
     *
     * @mbggenerated
     */
    DsTrmm selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ds_trmm
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(DsTrmm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ds_trmm
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(DsTrmm record);

    /**
     *查询指定时间类上中下旬的雨量总和均值
     * @param param
     * @return
     * @version <1> 2018-3-21 lxy:Created
     */
    List<TemTrmmTotalDataReturn> findTrmmByTenDays(TtnParam param);


    /**
     * 查询历史时间段上中下旬的雨量均值
     * @param param
     * @return
     * @version <1> 2018-3-22 lxy:Created
     */
    List<TenDaysTrmmDataReturn> findHistoryAvgForTrmmTotal(Map<String, Object> param);

    /**
     * 根据区域、作物、精度 查询数据时间列表
     * @param reportCreateParam
     * @return
     * @version<1> 2018-07-18 zhangshen: Created.
     */
    List<DsTrmm> queryDateTimeList(ReportCreateParam reportCreateParam);
}