package com.jh.forum.bbs.mapping;

import com.jh.forum.bbs.entity.ForumFreeDownload;

import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface IForumFreeDownloadMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table forum_free_download
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table forum_free_download
     *
     * @mbggenerated
     */
    int insert(ForumFreeDownload record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table forum_free_download
     *
     * @mbggenerated
     */
    int insertSelective(ForumFreeDownload record);


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table forum_free_download
     *
     * @mbggenerated
     */
    ForumFreeDownload selectByPrimaryKey(Integer id);


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table forum_free_download
     *
     * @mbggenerated
     */

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table forum_free_download
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ForumFreeDownload record);


    int countFree(Integer userId);
}