package com.jh.forum.bbs.mapping;

import com.jh.forum.bbs.entity.ForumCollectData;
import com.jh.forum.bbs.vo.MyCollectVo;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface IForumCollectDataMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table forum_collect_data
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table forum_collect_data
     *
     * @mbggenerated
     */
    int insert(ForumCollectData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table forum_collect_data
     *
     * @mbggenerated
     */
    int insertSelective(ForumCollectData record);


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table forum_collect_data
     *
     * @mbggenerated
     */
    ForumCollectData selectByPrimaryKey(Integer id);


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table forum_collect_data
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ForumCollectData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table forum_collect_data
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ForumCollectData record);


    void collectData(ForumCollectData record);

    void cancelData(ForumCollectData record);

    int selectCollectStatus(ForumCollectData record);

    List<MyCollectVo> queryMyCollect(Integer userId);
}