package com.jh.forum.bbs.mapping;


import com.jh.forum.bbs.entity.ForumOrderDetail;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;


@Mapper
public interface IForumOrderDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table forum_order_detail
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer orderId);


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table forum_order_detail
     *
     * @mbggenerated
     */
    int insertSelective(ForumOrderDetail record);



    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table forum_order_detail
     *
     * @mbggenerated
     */
    ForumOrderDetail selectByPrimaryKey(Integer orderId);


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table forum_order_detail
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ForumOrderDetail record);


    List<ForumOrderDetail> findDetailsByOrderNo(String OrdersNo);

}