package com.jh.forum.bbs.mapping;


import com.jh.forum.bbs.entity.ForumOrders;
import com.jh.forum.bbs.vo.OrdersVo;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface IForumOrdersMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table forum_orders
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    int deleteByOrderNo(String orderNo);


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table forum_orders
     *
     * @mbggenerated
     */
    int insertSelective(ForumOrders record);


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table forum_orders
     *
     * @mbggenerated
     */
    ForumOrders selectByPrimaryKey(Integer id);

    OrdersVo findOrderById(String tradeNo);


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table forum_orders
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ForumOrders record);

    List<OrdersVo> queryByType(OrdersVo ordersVo);

    int updateByStatus(OrdersVo ordersVo);

    int updateByPay(OrdersVo ordersVo);

    List<OrdersVo> findAllOrder(OrdersVo ordersVo);

}