package com.jh.briefing.entity;

public class GrowthRelativeTempManager {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column briefing_relative_temp_manager.relative_id
     *
     * @mbggenerated
     */
    private Integer relativeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column briefing_relative_temp_manager.growth_id
     *
     * @mbggenerated
     */
    private Integer growthId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column briefing_relative_temp_manager.growth_name
     *
     * @mbggenerated
     */
    private String growthName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column briefing_relative_temp_manager.temp_range_start
     *
     * @mbggenerated
     */
    private Integer tempRangeStart;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column briefing_relative_temp_manager.temp_range_end
     *
     * @mbggenerated
     */
    private Integer tempRangeEnd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column briefing_relative_temp_manager.instruction
     *
     * @mbggenerated
     */
    private String instruction;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column briefing_relative_temp_manager.ifavg
     *
     * @mbggenerated
     */
    private Short ifavg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column briefing_relative_temp_manager.if_or
     *
     * @mbggenerated
     */
    private Short ifOr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column briefing_relative_temp_manager.range_limit
     *
     * @mbggenerated
     */
    private Short rangeLimit;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column briefing_relative_temp_manager.relative_id
     *
     * @return the value of briefing_relative_temp_manager.relative_id
     *
     * @mbggenerated
     */
    public Integer getRelativeId() {
        return relativeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column briefing_relative_temp_manager.relative_id
     *
     * @param relativeId the value for briefing_relative_temp_manager.relative_id
     *
     * @mbggenerated
     */
    public void setRelativeId(Integer relativeId) {
        this.relativeId = relativeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column briefing_relative_temp_manager.growth_id
     *
     * @return the value of briefing_relative_temp_manager.growth_id
     *
     * @mbggenerated
     */
    public Integer getGrowthId() {
        return growthId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column briefing_relative_temp_manager.growth_id
     *
     * @param growthId the value for briefing_relative_temp_manager.growth_id
     *
     * @mbggenerated
     */
    public void setGrowthId(Integer growthId) {
        this.growthId = growthId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column briefing_relative_temp_manager.growth_name
     *
     * @return the value of briefing_relative_temp_manager.growth_name
     *
     * @mbggenerated
     */
    public String getGrowthName() {
        return growthName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column briefing_relative_temp_manager.growth_name
     *
     * @param growthName the value for briefing_relative_temp_manager.growth_name
     *
     * @mbggenerated
     */
    public void setGrowthName(String growthName) {
        this.growthName = growthName == null ? null : growthName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column briefing_relative_temp_manager.temp_range_start
     *
     * @return the value of briefing_relative_temp_manager.temp_range_start
     *
     * @mbggenerated
     */
    public Integer getTempRangeStart() {
        return tempRangeStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column briefing_relative_temp_manager.temp_range_start
     *
     * @param tempRangeStart the value for briefing_relative_temp_manager.temp_range_start
     *
     * @mbggenerated
     */
    public void setTempRangeStart(Integer tempRangeStart) {
        this.tempRangeStart = tempRangeStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column briefing_relative_temp_manager.temp_range_end
     *
     * @return the value of briefing_relative_temp_manager.temp_range_end
     *
     * @mbggenerated
     */
    public Integer getTempRangeEnd() {
        return tempRangeEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column briefing_relative_temp_manager.temp_range_end
     *
     * @param tempRangeEnd the value for briefing_relative_temp_manager.temp_range_end
     *
     * @mbggenerated
     */
    public void setTempRangeEnd(Integer tempRangeEnd) {
        this.tempRangeEnd = tempRangeEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column briefing_relative_temp_manager.instruction
     *
     * @return the value of briefing_relative_temp_manager.instruction
     *
     * @mbggenerated
     */
    public String getInstruction() {
        return instruction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column briefing_relative_temp_manager.instruction
     *
     * @param instruction the value for briefing_relative_temp_manager.instruction
     *
     * @mbggenerated
     */
    public void setInstruction(String instruction) {
        this.instruction = instruction == null ? null : instruction.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column briefing_relative_temp_manager.ifavg
     *
     * @return the value of briefing_relative_temp_manager.ifavg
     *
     * @mbggenerated
     */
    public Short getIfavg() {
        return ifavg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column briefing_relative_temp_manager.ifavg
     *
     * @param ifavg the value for briefing_relative_temp_manager.ifavg
     *
     * @mbggenerated
     */
    public void setIfavg(Short ifavg) {
        this.ifavg = ifavg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column briefing_relative_temp_manager.if_or
     *
     * @return the value of briefing_relative_temp_manager.if_or
     *
     * @mbggenerated
     */
    public Short getIfOr() {
        return ifOr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column briefing_relative_temp_manager.if_or
     *
     * @param ifOr the value for briefing_relative_temp_manager.if_or
     *
     * @mbggenerated
     */
    public void setIfOr(Short ifOr) {
        this.ifOr = ifOr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column briefing_relative_temp_manager.range_limit
     *
     * @return the value of briefing_relative_temp_manager.range_limit
     *
     * @mbggenerated
     */
    public Short getRangeLimit() {
        return rangeLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column briefing_relative_temp_manager.range_limit
     *
     * @param rangeLimit the value for briefing_relative_temp_manager.range_limit
     *
     * @mbggenerated
     */
    public void setRangeLimit(Short rangeLimit) {
        this.rangeLimit = rangeLimit;
    }
}