package com.jh.briefing.entity;

import java.util.Date;

public class GrowthDiseaseManager {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column briefing_disease_all_manager.disease_id
     *
     * @mbggenerated
     */
    private Integer diseaseId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column briefing_disease_all_manager.growth_id
     *
     * @mbggenerated
     */
    private Integer growthId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column briefing_disease_all_manager.disease_name
     *
     * @mbggenerated
     */
    private String diseaseName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column briefing_disease_all_manager.disease_measure
     *
     * @mbggenerated
     */
    private String diseaseMeasure;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column briefing_disease_all_manager.disease_remark
     *
     * @mbggenerated
     */
    private String diseaseRemark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column briefing_disease_all_manager.crops_id
     *
     * @mbggenerated
     */
    private Integer cropsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column briefing_disease_all_manager.modify_time
     *
     * @mbggenerated
     */
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column briefing_disease_all_manager.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column briefing_disease_all_manager.disease_type
     *
     * @mbggenerated
     */
    private Integer diseaseType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column briefing_disease_all_manager.disease_img
     *
     * @mbggenerated
     */
    private String diseaseImg;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column briefing_disease_all_manager.disease_id
     *
     * @return the value of briefing_disease_all_manager.disease_id
     *
     * @mbggenerated
     */
    public Integer getDiseaseId() {
        return diseaseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column briefing_disease_all_manager.disease_id
     *
     * @param diseaseId the value for briefing_disease_all_manager.disease_id
     *
     * @mbggenerated
     */
    public void setDiseaseId(Integer diseaseId) {
        this.diseaseId = diseaseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column briefing_disease_all_manager.growth_id
     *
     * @return the value of briefing_disease_all_manager.growth_id
     *
     * @mbggenerated
     */
    public Integer getGrowthId() {
        return growthId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column briefing_disease_all_manager.growth_id
     *
     * @param growthId the value for briefing_disease_all_manager.growth_id
     *
     * @mbggenerated
     */
    public void setGrowthId(Integer growthId) {
        this.growthId = growthId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column briefing_disease_all_manager.disease_name
     *
     * @return the value of briefing_disease_all_manager.disease_name
     *
     * @mbggenerated
     */
    public String getDiseaseName() {
        return diseaseName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column briefing_disease_all_manager.disease_name
     *
     * @param diseaseName the value for briefing_disease_all_manager.disease_name
     *
     * @mbggenerated
     */
    public void setDiseaseName(String diseaseName) {
        this.diseaseName = diseaseName == null ? null : diseaseName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column briefing_disease_all_manager.disease_measure
     *
     * @return the value of briefing_disease_all_manager.disease_measure
     *
     * @mbggenerated
     */
    public String getDiseaseMeasure() {
        return diseaseMeasure;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column briefing_disease_all_manager.disease_measure
     *
     * @param diseaseMeasure the value for briefing_disease_all_manager.disease_measure
     *
     * @mbggenerated
     */
    public void setDiseaseMeasure(String diseaseMeasure) {
        this.diseaseMeasure = diseaseMeasure == null ? null : diseaseMeasure.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column briefing_disease_all_manager.disease_remark
     *
     * @return the value of briefing_disease_all_manager.disease_remark
     *
     * @mbggenerated
     */
    public String getDiseaseRemark() {
        return diseaseRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column briefing_disease_all_manager.disease_remark
     *
     * @param diseaseRemark the value for briefing_disease_all_manager.disease_remark
     *
     * @mbggenerated
     */
    public void setDiseaseRemark(String diseaseRemark) {
        this.diseaseRemark = diseaseRemark == null ? null : diseaseRemark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column briefing_disease_all_manager.crops_id
     *
     * @return the value of briefing_disease_all_manager.crops_id
     *
     * @mbggenerated
     */
    public Integer getCropsId() {
        return cropsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column briefing_disease_all_manager.crops_id
     *
     * @param cropsId the value for briefing_disease_all_manager.crops_id
     *
     * @mbggenerated
     */
    public void setCropsId(Integer cropsId) {
        this.cropsId = cropsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column briefing_disease_all_manager.modify_time
     *
     * @return the value of briefing_disease_all_manager.modify_time
     *
     * @mbggenerated
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column briefing_disease_all_manager.modify_time
     *
     * @param modifyTime the value for briefing_disease_all_manager.modify_time
     *
     * @mbggenerated
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column briefing_disease_all_manager.create_time
     *
     * @return the value of briefing_disease_all_manager.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column briefing_disease_all_manager.create_time
     *
     * @param createTime the value for briefing_disease_all_manager.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column briefing_disease_all_manager.disease_type
     *
     * @return the value of briefing_disease_all_manager.disease_type
     *
     * @mbggenerated
     */
    public Integer getDiseaseType() {
        return diseaseType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column briefing_disease_all_manager.disease_type
     *
     * @param diseaseType the value for briefing_disease_all_manager.disease_type
     *
     * @mbggenerated
     */
    public void setDiseaseType(Integer diseaseType) {
        this.diseaseType = diseaseType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column briefing_disease_all_manager.disease_img
     *
     * @return the value of briefing_disease_all_manager.disease_img
     *
     * @mbggenerated
     */
    public String getDiseaseImg() {
        return diseaseImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column briefing_disease_all_manager.disease_img
     *
     * @param diseaseImg the value for briefing_disease_all_manager.disease_img
     *
     * @mbggenerated
     */
    public void setDiseaseImg(String diseaseImg) {
        this.diseaseImg = diseaseImg == null ? null : diseaseImg.trim();
    }
}