package com.jh.forum.bbs.entity;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.jh.entity.BaseEntity;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.util.Date;

public class ForumDownloadData extends BaseEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column forum_download_data.data_id
     *
     * @mbggenerated
     */
    private Integer dataId;


    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column forum_download_data.region_id
     *
     * @mbggenerated
     */
    private Long regionId;


    private String regionCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column forum_download_data.crop_id
     *
     * @mbggenerated
     */
    private Integer cropId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column forum_download_data.accuracy
     *
     * @mbggenerated
     */
    private Integer accuracy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column forum_download_data.data_classify
     *
     * @mbggenerated
     */
    private Integer dataClassify;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column forum_download_data.data_time
     *
     * @mbggenerated
     */
    @JsonFormat(pattern = "yyyy-MM-dd")
    private LocalDate dataTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column forum_download_data.data_path
     *
     * @mbggenerated
     */
    private String dataPath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column forum_download_data.data_flag
     *
     * @mbggenerated
     */
    private Integer dataFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column forum_download_data.data_introduction
     *
     * @mbggenerated
     */
    private String dataIntroduction;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column forum_download_data.data_content
     *
     * @mbggenerated
     */
    private String dataContent;

    private String dataTitle;


    private Integer pushStatus;

    private String sonType;

    private String parentType;

    private BigDecimal price;

    private String dataType;

    private Integer downloadNum;

    private Integer collectNum;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column forum_download_data.data_id
     *
     * @return the value of forum_download_data.data_id
     *
     * @mbggenerated
     */
    public Integer getDataId() {
        return dataId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column forum_download_data.data_id
     *
     * @param dataId the value for forum_download_data.data_id
     *
     * @mbggenerated
     */
    public void setDataId(Integer dataId) {
        this.dataId = dataId;
    }


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column forum_download_data.region_id
     *
     * @return the value of forum_download_data.region_id
     *
     * @mbggenerated
     */
    public Long getRegionId() {
        return regionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column forum_download_data.region_id
     *
     * @param regionId the value for forum_download_data.region_id
     *
     * @mbggenerated
     */
    public void setRegionId(Long regionId) {
        this.regionId = regionId;
    }

    public String getRegionCode() {
        return regionCode;
    }

    public void setRegionCode(String regionCode) {
        this.regionCode = regionCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column forum_download_data.crop_id
     *
     * @return the value of forum_download_data.crop_id
     *
     * @mbggenerated
     */
    public Integer getCropId() {
        return cropId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column forum_download_data.crop_id
     *
     * @param cropId the value for forum_download_data.crop_id
     *
     * @mbggenerated
     */
    public void setCropId(Integer cropId) {
        this.cropId = cropId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column forum_download_data.accuracy
     *
     * @return the value of forum_download_data.accuracy
     *
     * @mbggenerated
     */
    public Integer getAccuracy() {
        return accuracy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column forum_download_data.accuracy
     *
     * @param accuracy the value for forum_download_data.accuracy
     *
     * @mbggenerated
     */
    public void setAccuracy(Integer accuracy) {
        this.accuracy = accuracy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column forum_download_data.data_classify
     *
     * @return the value of forum_download_data.data_classify
     *
     * @mbggenerated
     */
    public Integer getDataClassify() {
        return dataClassify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column forum_download_data.data_classify
     *
     * @param dataClassify the value for forum_download_data.data_classify
     *
     * @mbggenerated
     */
    public void setDataClassify(Integer dataClassify) {
        this.dataClassify = dataClassify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column forum_download_data.data_time
     *
     * @return the value of forum_download_data.data_time
     *
     * @mbggenerated
     */
    public LocalDate getDataTime() {
        return dataTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column forum_download_data.data_time
     *
     * @param dataTime the value for forum_download_data.data_time
     *
     * @mbggenerated
     */
    public void setDataTime(LocalDate dataTime) {
        this.dataTime = dataTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column forum_download_data.data_path
     *
     * @return the value of forum_download_data.data_path
     *
     * @mbggenerated
     */
    public String getDataPath() {
        return dataPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column forum_download_data.data_path
     *
     * @param dataPath the value for forum_download_data.data_path
     *
     * @mbggenerated
     */
    public void setDataPath(String dataPath) {
        this.dataPath = dataPath == null ? null : dataPath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column forum_download_data.data_flag
     *
     * @return the value of forum_download_data.data_flag
     *
     * @mbggenerated
     */
    public Integer getDataFlag() {
        return dataFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column forum_download_data.data_flag
     *
     * @param dataFlag the value for forum_download_data.data_flag
     *
     * @mbggenerated
     */
    public void setDataFlag(Integer dataFlag) {
        this.dataFlag = dataFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column forum_download_data.data_introduction
     *
     * @return the value of forum_download_data.data_introduction
     *
     * @mbggenerated
     */
    public String getDataIntroduction() {
        return dataIntroduction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column forum_download_data.data_introduction
     *
     * @param dataIntroduction the value for forum_download_data.data_introduction
     *
     * @mbggenerated
     */
    public void setDataIntroduction(String dataIntroduction) {
        this.dataIntroduction = dataIntroduction == null ? null : dataIntroduction.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column forum_download_data.data_content
     *
     * @return the value of forum_download_data.data_content
     *
     * @mbggenerated
     */
    public String getDataContent() {
        return dataContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column forum_download_data.data_content
     *
     * @param dataContent the value for forum_download_data.data_content
     *
     * @mbggenerated
     */
    public void setDataContent(String dataContent) {
        this.dataContent = dataContent == null ? null : dataContent.trim();
    }

    public String getDataTitle() {
        return dataTitle;
    }

    public void setDataTitle(String dataTitle) {
        this.dataTitle = dataTitle;
    }

    public Integer getPushStatus() {
        return pushStatus;
    }

    public void setPushStatus(Integer pushStatus) {
        this.pushStatus = pushStatus;
    }

    public String getSonType() {

        return sonType;
    }

    public void setSonType(String sonType) {
        this.sonType = sonType;
    }

    public String getParentType() {
        return parentType;
    }

    public void setParentType(String parentType) {
        this.parentType = parentType;
    }

    public BigDecimal getPrice() {
        return price;
    }

    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    public String getDataType() {
        return dataType;
    }

    public void setDataType(String dataType) {
        this.dataType = dataType;
    }

    public Integer getDownloadNum() {
        return downloadNum;
    }

    public void setDownloadNum(Integer downloadNum) {
        this.downloadNum = downloadNum;
    }

    public Integer getCollectNum() {
        return collectNum;
    }

    public void setCollectNum(Integer collectNum) {
        this.collectNum = collectNum;
    }
}