package com.jh.forum.bbs.entity;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.jh.entity.BaseEntity;
import org.springframework.format.annotation.DateTimeFormat;

import java.time.LocalDate;
import java.util.Date;

public class ForumOrderData extends BaseEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column forum_order_data.order_id
     *
     * @mbggenerated
     */
    private Integer orderId;


    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column forum_order_data.region_id
     *
     * @mbggenerated
     */
    private Long regionId;


    private String regionCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column forum_order_data.crop_id
     *
     * @mbggenerated
     */
    private String crop;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column forum_order_data.accuracy_range
     *
     * @mbggenerated
     */
    private String accuracyRange;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column forum_order_data.data_classify
     *
     * @mbggenerated
     */
    private String dataClassify;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column forum_order_data.start_date
     *
     * @mbggenerated
     */
    @JsonFormat(pattern = "yyyy-MM-dd")
    @DateTimeFormat(pattern="yyyy-MM-dd")
    private LocalDate startDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column forum_order_data.end_date
     *
     * @mbggenerated
     */
    @JsonFormat(pattern = "yyyy-MM-dd")
    @DateTimeFormat(pattern="yyyy-MM-dd")
    private LocalDate endDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column forum_order_data.data_show
     *
     * @mbggenerated
     */
    private Integer dataShow;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column forum_order_data.order_tel
     *
     * @mbggenerated
     */
    private String orderTel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column forum_order_data.order_status
     *
     * @mbggenerated
     */
    private String orderStatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column forum_order_data.order_id
     *
     * @return the value of forum_order_data.order_id
     *
     * @mbggenerated
     */
    public Integer getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column forum_order_data.order_id
     *
     * @param orderId the value for forum_order_data.order_id
     *
     * @mbggenerated
     */
    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column forum_order_data.region_id
     *
     * @return the value of forum_order_data.region_id
     *
     * @mbggenerated
     */
    public Long getRegionId() {
        return regionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column forum_order_data.region_id
     *
     * @param regionId the value for forum_order_data.region_id
     *
     * @mbggenerated
     */
    public void setRegionId(Long regionId) {
        this.regionId = regionId;
    }

    public String getRegionCode() {
        return regionCode;
    }

    public void setRegionCode(String regionCode) {
        this.regionCode = regionCode;
    }

    public String getCrop() {
        return crop;
    }

    public void setCrop(String crop) {
        this.crop = crop;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column forum_order_data.accuracy_range
     *
     * @return the value of forum_order_data.accuracy_range
     *
     * @mbggenerated
     */
    public String getAccuracyRange() {
        return accuracyRange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column forum_order_data.accuracy_range
     *
     * @param accuracyRange the value for forum_order_data.accuracy_range
     *
     * @mbggenerated
     */
    public void setAccuracyRange(String accuracyRange) {
        this.accuracyRange = accuracyRange == null ? null : accuracyRange.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column forum_order_data.data_classify
     *
     * @return the value of forum_order_data.data_classify
     *
     * @mbggenerated
     */
    public String getDataClassify() {
        return dataClassify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column forum_order_data.data_classify
     *
     * @param dataClassify the value for forum_order_data.data_classify
     *
     * @mbggenerated
     */
    public void setDataClassify(String dataClassify) {
        this.dataClassify = dataClassify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column forum_order_data.start_date
     *
     * @return the value of forum_order_data.start_date
     *
     * @mbggenerated
     */
    public LocalDate getStartDate() {
        return startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column forum_order_data.start_date
     *
     * @param startDate the value for forum_order_data.start_date
     *
     * @mbggenerated
     */
    public void setStartDate(LocalDate startDate) {
        this.startDate = startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column forum_order_data.end_date
     *
     * @return the value of forum_order_data.end_date
     *
     * @mbggenerated
     */
    public LocalDate getEndDate() {
        return endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column forum_order_data.end_date
     *
     * @param endDate the value for forum_order_data.end_date
     *
     * @mbggenerated
     */
    public void setEndDate(LocalDate endDate) {
        this.endDate = endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column forum_order_data.data_show
     *
     * @return the value of forum_order_data.data_show
     *
     * @mbggenerated
     */
    public Integer getDataShow() {
        return dataShow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column forum_order_data.data_show
     *
     * @param dataShow the value for forum_order_data.data_show
     *
     * @mbggenerated
     */
    public void setDataShow(Integer dataShow) {
        this.dataShow = dataShow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column forum_order_data.order_tel
     *
     * @return the value of forum_order_data.order_tel
     *
     * @mbggenerated
     */
    public String getOrderTel() {
        return orderTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column forum_order_data.order_tel
     *
     * @param orderTel the value for forum_order_data.order_tel
     *
     * @mbggenerated
     */
    public void setOrderTel(String orderTel) {
        this.orderTel = orderTel == null ? null : orderTel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column forum_order_data.order_status
     *
     * @return the value of forum_order_data.order_status
     *
     * @mbggenerated
     */
    public String getOrderStatus() {
        return orderStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column forum_order_data.order_status
     *
     * @param orderStatus the value for forum_order_data.order_status
     *
     * @mbggenerated
     */
    public void setOrderStatus(String orderStatus) {
        this.orderStatus = orderStatus == null ? null : orderStatus.trim();
    }
}