package com.jh.forum.bbs.entity;

import java.util.Date;

public class ForumCollectData {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column forum_collect_data.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column forum_collect_data.data_id
     *
     * @mbggenerated
     */
    private Integer dataId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column forum_collect_data.user_id
     *
     * @mbggenerated
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column forum_collect_data.collect_time
     *
     * @mbggenerated
     */
    private Date collectTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column forum_collect_data.id
     *
     * @return the value of forum_collect_data.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column forum_collect_data.id
     *
     * @param id the value for forum_collect_data.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column forum_collect_data.data_id
     *
     * @return the value of forum_collect_data.data_id
     *
     * @mbggenerated
     */
    public Integer getDataId() {
        return dataId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column forum_collect_data.data_id
     *
     * @param dataId the value for forum_collect_data.data_id
     *
     * @mbggenerated
     */
    public void setDataId(Integer dataId) {
        this.dataId = dataId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column forum_collect_data.user_id
     *
     * @return the value of forum_collect_data.user_id
     *
     * @mbggenerated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column forum_collect_data.user_id
     *
     * @param userId the value for forum_collect_data.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column forum_collect_data.collect_time
     *
     * @return the value of forum_collect_data.collect_time
     *
     * @mbggenerated
     */
    public Date getCollectTime() {
        return collectTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column forum_collect_data.collect_time
     *
     * @param collectTime the value for forum_collect_data.collect_time
     *
     * @mbggenerated
     */
    public void setCollectTime(Date collectTime) {
        this.collectTime = collectTime;
    }
}