package com.jh.cltApp.entity;

import com.jh.entity.BaseEntity;

public class CltMediaSource extends BaseEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column clt_media_source.media_id
     *
     * @mbggenerated
     */
    private Integer mediaId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column clt_media_source.item_id
     *
     * @mbggenerated
     */
    private Integer itemId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column clt_media_source.media_type
     *
     * @mbggenerated
     */
    private Integer mediaType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column clt_media_source.sound_time
     *
     * @mbggenerated
     */
    private Integer soundTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column clt_media_source.media_path
     *
     * @mbggenerated
     */
    private String mediaPath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column clt_media_source.index
     *
     * @mbggenerated
     */
    private Integer index;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column clt_media_source.media_id
     *
     * @return the value of clt_media_source.media_id
     *
     * @mbggenerated
     */
    public Integer getMediaId() {
        return mediaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column clt_media_source.media_id
     *
     * @param mediaId the value for clt_media_source.media_id
     *
     * @mbggenerated
     */
    public void setMediaId(Integer mediaId) {
        this.mediaId = mediaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column clt_media_source.item_id
     *
     * @return the value of clt_media_source.item_id
     *
     * @mbggenerated
     */
    public Integer getItemId() {
        return itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column clt_media_source.item_id
     *
     * @param itemId the value for clt_media_source.item_id
     *
     * @mbggenerated
     */
    public void setItemId(Integer itemId) {
        this.itemId = itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column clt_media_source.media_type
     *
     * @return the value of clt_media_source.media_type
     *
     * @mbggenerated
     */
    public Integer getMediaType() {
        return mediaType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column clt_media_source.media_type
     *
     * @param mediaType the value for clt_media_source.media_type
     *
     * @mbggenerated
     */
    public void setMediaType(Integer mediaType) {
        this.mediaType = mediaType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column clt_media_source.sound_time
     *
     * @return the value of clt_media_source.sound_time
     *
     * @mbggenerated
     */
    public Integer getSoundTime() {
        return soundTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column clt_media_source.sound_time
     *
     * @param soundTime the value for clt_media_source.sound_time
     *
     * @mbggenerated
     */
    public void setSoundTime(Integer soundTime) {
        this.soundTime = soundTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column clt_media_source.media_path
     *
     * @return the value of clt_media_source.media_path
     *
     * @mbggenerated
     */
    public String getMediaPath() {
        return mediaPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column clt_media_source.media_path
     *
     * @param mediaPath the value for clt_media_source.media_path
     *
     * @mbggenerated
     */
    public void setMediaPath(String mediaPath) {
        this.mediaPath = mediaPath == null ? null : mediaPath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column clt_media_source.index
     *
     * @return the value of clt_media_source.index
     *
     * @mbggenerated
     */
    public Integer getIndex() {
        return index;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column clt_media_source.index
     *
     * @param index the value for clt_media_source.index
     *
     * @mbggenerated
     */
    public void setIndex(Integer index) {
        this.index = index;
    }
}