package com.jh.cltApp.entity;

import com.jh.entity.BaseEntity;

public class CltTaskUser extends BaseEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column clt_task_user.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column clt_task_user.task_id
     *
     * @mbggenerated
     */
    private Integer taskId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column clt_task_user.account_id
     *
     * @mbggenerated
     */
    private Integer accountId;

    private String isShoulder;//是否是负责人

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column clt_task_user.id
     *
     * @return the value of clt_task_user.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column clt_task_user.id
     *
     * @param id the value for clt_task_user.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column clt_task_user.task_id
     *
     * @return the value of clt_task_user.task_id
     *
     * @mbggenerated
     */
    public Integer getTaskId() {
        return taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column clt_task_user.task_id
     *
     * @param taskId the value for clt_task_user.task_id
     *
     * @mbggenerated
     */
    public void setTaskId(Integer taskId) {
        this.taskId = taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column clt_task_user.account_id
     *
     * @return the value of clt_task_user.account_id
     *
     * @mbggenerated
     */
    public Integer getAccountId() {
        return accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column clt_task_user.account_id
     *
     * @param accountId the value for clt_task_user.account_id
     *
     * @mbggenerated
     */
    public void setAccountId(Integer accountId) {
        this.accountId = accountId;
    }

    public String getIsShoulder() {
        return isShoulder;
    }

    public void setIsShoulder(String isShoulder) {
        this.isShoulder = isShoulder;
    }
}