package com.jh.cltApp.entity;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.jh.entity.BaseEntity;

import java.time.LocalDateTime;
import java.util.Date;

public class CltTaskItem extends BaseEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column clt_task_item.item_id
     *
     * @mbggenerated
     */
    private Integer itemId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column clt_task_item.task_id
     *
     * @mbggenerated
     */
    private Integer taskId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column clt_task_item.item_name
     *
     * @mbggenerated
     */
    private String itemName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column clt_task_item.survey_time
     *
     * @mbggenerated
     */
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private LocalDateTime surveyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column clt_task_item.position
     *
     * @mbggenerated
     */
    private String position;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column clt_task_item.region_id
     *
     * @mbggenerated
     */
    private Long regionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column clt_task_item.survey_address
     *
     * @mbggenerated
     */
    private String surveyAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column clt_task_item.content_xml
     *
     * @mbggenerated
     */
    private String contentXml;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column clt_task_item.item_id
     *
     * @return the value of clt_task_item.item_id
     *
     * @mbggenerated
     */
    public Integer getItemId() {
        return itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column clt_task_item.item_id
     *
     * @param itemId the value for clt_task_item.item_id
     *
     * @mbggenerated
     */
    public void setItemId(Integer itemId) {
        this.itemId = itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column clt_task_item.task_id
     *
     * @return the value of clt_task_item.task_id
     *
     * @mbggenerated
     */
    public Integer getTaskId() {
        return taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column clt_task_item.task_id
     *
     * @param taskId the value for clt_task_item.task_id
     *
     * @mbggenerated
     */
    public void setTaskId(Integer taskId) {
        this.taskId = taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column clt_task_item.item_name
     *
     * @return the value of clt_task_item.item_name
     *
     * @mbggenerated
     */
    public String getItemName() {
        return itemName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column clt_task_item.item_name
     *
     * @param itemName the value for clt_task_item.item_name
     *
     * @mbggenerated
     */
    public void setItemName(String itemName) {
        this.itemName = itemName == null ? null : itemName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column clt_task_item.survey_time
     *
     * @return the value of clt_task_item.survey_time
     *
     * @mbggenerated
     */
    public LocalDateTime getSurveyTime() {
        return surveyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column clt_task_item.survey_time
     *
     * @param surveyTime the value for clt_task_item.survey_time
     *
     * @mbggenerated
     */
    public void setSurveyTime(LocalDateTime surveyTime) {
        this.surveyTime = surveyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column clt_task_item.position
     *
     * @return the value of clt_task_item.position
     *
     * @mbggenerated
     */
    public String getPosition() {
        return position;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column clt_task_item.position
     *
     * @param position the value for clt_task_item.position
     *
     * @mbggenerated
     */
    public void setPosition(String position) {
        this.position = position == null ? null : position.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column clt_task_item.region_id
     *
     * @return the value of clt_task_item.region_id
     *
     * @mbggenerated
     */
    public Long getRegionId() {
        return regionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column clt_task_item.region_id
     *
     * @param regionId the value for clt_task_item.region_id
     *
     * @mbggenerated
     */
    public void setRegionId(Long regionId) {
        this.regionId = regionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column clt_task_item.survey_address
     *
     * @return the value of clt_task_item.survey_address
     *
     * @mbggenerated
     */
    public String getSurveyAddress() {
        return surveyAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column clt_task_item.survey_address
     *
     * @param surveyAddress the value for clt_task_item.survey_address
     *
     * @mbggenerated
     */
    public void setSurveyAddress(String surveyAddress) {
        this.surveyAddress = surveyAddress == null ? null : surveyAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column clt_task_item.content_xml
     *
     * @return the value of clt_task_item.content_xml
     *
     * @mbggenerated
     */
    public String getContentXml() {
        return contentXml;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column clt_task_item.content_xml
     *
     * @param contentXml the value for clt_task_item.content_xml
     *
     * @mbggenerated
     */
    public void setContentXml(String contentXml) {
        this.contentXml = contentXml == null ? null : contentXml.trim();
    }
}