package com.jh.forum.bbs.vo;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.jh.forum.bbs.entity.ForumOrderDetail;
import com.jh.forum.bbs.entity.ForumOrders;
import org.springframework.format.annotation.DateTimeFormat;

import java.time.LocalDate;
import java.util.List;

public class OrdersVo extends ForumOrders {

    private Integer creator;

    private String dataPath;

    private List<Integer> idList;

    private List<ForumOrderDetail> detailsList;

    /**
     * 订单名称
     */
    private String subject;
    /**
     * 商户网站唯一订单号
     */
    private String order_no;
    /**
     * 付款金额
     */
    private String total_amount;
    /**
     * 商品描述
     */
    private String goods_detail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column forum_order_data.start_date
     *
     * @mbggenerated
     */
    private String startDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column forum_order_data.end_date
     *
     * @mbggenerated
     */
    private String endDate;

    private Integer payStatus;

    @Override
    public Integer getCreator() {
        return creator;
    }

    @Override
    public void setCreator(Integer creator) {
        this.creator = creator;
    }

    public List<Integer> getIdList() {
        return idList;
    }

    public void setIdList(List<Integer> idList) {
        this.idList = idList;
    }

    public List<ForumOrderDetail> getDetailsList() {
        return detailsList;
    }

    public void setDetailsList(List<ForumOrderDetail> detailsList) {
        this.detailsList = detailsList;
    }


    @Override
    public String getSubject() {
        return subject;
    }

    @Override
    public void setSubject(String subject) {
        this.subject = subject;
    }

    public String getOrder_no() {
        return order_no;
    }

    public void setOrder_no(String order_no) {
        this.order_no = order_no;
    }

    public void setTotal_amount(String total_amount) {
        this.total_amount = total_amount;
    }

    public String getGoods_detail() {
        return goods_detail;
    }

    public void setGoods_detail(String goods_detail) {
        this.goods_detail = goods_detail;
    }

    public String getDataPath() {
        return dataPath;
    }

    public void setDataPath(String dataPath) {
        this.dataPath = dataPath;
    }

    public String getTotal_amount() {
        return total_amount;
    }

    public String getStartDate() {
        return startDate;
    }

    public void setStartDate(String startDate) {
        this.startDate = startDate;
    }

    public String getEndDate() {
        return endDate;
    }

    public void setEndDate(String endDate) {
        this.endDate = endDate;
    }

    @Override
    public Integer getPayStatus() {
        return payStatus;
    }

    @Override
    public void setPayStatus(Integer payStatus) {
        this.payStatus = payStatus;
    }
}
