package com.jh.forum.bbs.vo;

import com.jh.entity.BaseEntity;

import javax.print.DocFlavor;

public class OrdersDetailVo extends BaseEntity {

    private Integer orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column forum_order_detail.data_status
     *
     * @mbggenerated
     */
    private String dataStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column forum_order_detail.del_flag
     *
     * @mbggenerated
     */
    private String delFlag;



    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column forum_order_detail.creator_name
     *
     * @mbggenerated
     */
    private String creatorName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column forum_order_detail.creator
     *
     * @mbggenerated
     */
    private Integer creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column forum_order_detail.modify_time
     *
     * @mbggenerated
     */
    private String modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column forum_order_detail.modifier_name
     *
     * @mbggenerated
     */

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column forum_order_detail.modifier
     *
     * @mbggenerated
     */
    private Integer modifier;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column forum_order_detail.data_id
     *
     * @mbggenerated
     */
    private Integer dataId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column forum_order_detail.classify_name
     *
     * @mbggenerated
     */
    private String classifyName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column forum_order_detail.region_name
     *
     * @mbggenerated
     */
    private String regionName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column forum_order_detail.accuracy_name
     *
     * @mbggenerated
     */
    private String accuracyName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column forum_order_detail.unit_price
     *
     * @mbggenerated
     */
    private String unitPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column forum_order_detail.num
     *
     * @mbggenerated
     */
    private Integer num;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column forum_order_detail.price
     *
     * @mbggenerated
     */
    private String price;

    private String orderNo;


    private String cropName;


    private String dataTime;


    private String dataName;

    private String dataPath;

    private String dataPackagePath;


    public Integer getOrderId() {
        return orderId;
    }

    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }

    @Override
    public String getDataStatus() {
        return dataStatus;
    }

    @Override
    public void setDataStatus(String dataStatus) {
        this.dataStatus = dataStatus;
    }

    @Override
    public String getDelFlag() {
        return delFlag;
    }

    @Override
    public void setDelFlag(String delFlag) {
        this.delFlag = delFlag;
    }


    @Override
    public String getCreatorName() {
        return creatorName;
    }

    @Override
    public void setCreatorName(String creatorName) {
        this.creatorName = creatorName;
    }

    @Override
    public Integer getCreator() {
        return creator;
    }

    @Override
    public void setCreator(Integer creator) {
        this.creator = creator;
    }



    @Override
    public Integer getModifier() {
        return modifier;
    }

    @Override
    public void setModifier(Integer modifier) {
        this.modifier = modifier;
    }

    public Integer getDataId() {
        return dataId;
    }

    public void setDataId(Integer dataId) {
        this.dataId = dataId;
    }

    public String getClassifyName() {
        return classifyName;
    }

    public void setClassifyName(String classifyName) {
        this.classifyName = classifyName;
    }

    public String getRegionName() {
        return regionName;
    }

    public void setRegionName(String regionName) {
        this.regionName = regionName;
    }

    public String getAccuracyName() {
        return accuracyName;
    }

    public void setAccuracyName(String accuracyName) {
        this.accuracyName = accuracyName;
    }

    public Integer getNum() {
        return num;
    }

    public void setNum(Integer num) {
        this.num = num;
    }

    public String getOrderNo() {
        return orderNo;
    }

    public void setOrderNo(String orderNo) {
        this.orderNo = orderNo;
    }

    public String getCropName() {
        return cropName;
    }

    public void setCropName(String cropName) {
        this.cropName = cropName;
    }

    public String getDataTime() {
        return dataTime;
    }

    public void setDataTime(String dataTime) {
        this.dataTime = dataTime;
    }

    public String getDataName() {
        return dataName;
    }

    public void setDataName(String dataName) {
        this.dataName = dataName;
    }

    public String getDataPath() {
        return dataPath;
    }

    public void setDataPath(String dataPath) {
        this.dataPath = dataPath;
    }

    public String getDataPackagePath() {
        return dataPackagePath;
    }

    public void setDataPackagePath(String dataPackagePath) {
        this.dataPackagePath = dataPackagePath;
    }

    public String getUnitPrice() {
        return unitPrice;
    }

    public void setUnitPrice(String unitPrice) {
        this.unitPrice = unitPrice;
    }

    public String getPrice() {
        return price;
    }

    public void setPrice(String price) {
        this.price = price;
    }
}
