package com.jh.data.entity;

import com.fasterxml.jackson.annotation.JsonFormat;
import io.swagger.annotations.ApiModelProperty;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalDateTime;

public class DsT {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ds_t.id
     *
     * @mbggenerated
     */
    private Integer id;//主键id

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ds_t.region_id
     *
     * @mbggenerated
     */
    private Long regionId;//区域id

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ds_t.remark
     *
     * @mbggenerated
     */
    private String remark;//备注

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ds_t.data_status
     *
     * @mbggenerated
     */
    private String dataStatus;//是否有效

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ds_t.create_time
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "创建时间")
    @JsonFormat(pattern = "yyyy-MM-dd")
    private LocalDate createTime;//创建时间

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ds_t.creator_name
     *
     * @mbggenerated
     */
    private String creatorName;//创建人名称

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ds_t.creator
     *
     * @mbggenerated
     */
    private Long creator;//创建人id

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ds_t.modify_time
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "更新时间")
    @JsonFormat(pattern = "yyyy-MM-dd")
    private LocalDate modifyTime;//更新时间

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ds_t.modifier_name
     *
     * @mbggenerated
     */
    private String modifierName;//更新操作人名称

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ds_t.modifier
     *
     * @mbggenerated
     */
    private Integer modifier;//更新操作人

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ds_t.t
     *
     * @mbggenerated
     */
    private BigDecimal t;//区域地温均值1km

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ds_t.t_max
     *
     * @mbggenerated
     */
    private BigDecimal tMax;//区域地温最大值1km

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ds_t.t_min
     *
     * @mbggenerated
     */
    private BigDecimal tMin;//区域地温最小值1km

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ds_t.t_stddev
     *
     * @mbggenerated
     */
    private BigDecimal tStddev;//区域地温标准差值1km

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ds_t.data_time
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "数据时间")
    @JsonFormat(pattern = "yyyy-MM-dd")
    private LocalDate dataTime;//数据时间

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ds_t.publish_status
     *
     * @mbggenerated
     */
    private Integer publishStatus;//发布状态

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ds_t.publish_time
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "发布时间")
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private LocalDateTime publishTime;//发布时间

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ds_t.publisher_name
     *
     * @mbggenerated
     */
    private String publisherName;//发布人名称

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ds_t.del_flag
     *
     * @mbggenerated
     */
    private String delFlag;//删除标识

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ds_t.publisher
     *
     * @mbggenerated
     */
    private Integer publisher;//发布人

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ds_t.data_type
     *
     * @mbggenerated
     */
    private Integer dataType;//卫星类型

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ds_t.resolution
     *
     * @mbggenerated
     */
    private Integer resolution;//精度

    private String regionName;//区域中文名

    private String regionCode;//区域Code

    private  String resolutionValue;//精度值


    private String publishStatusName;//发布状态

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ds_t.id
     *
     * @return the value of ds_t.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ds_t.id
     *
     * @param id the value for ds_t.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ds_t.region_id
     *
     * @return the value of ds_t.region_id
     *
     * @mbggenerated
     */
    public Long getRegionId() {
        return regionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ds_t.region_id
     *
     * @param regionId the value for ds_t.region_id
     *
     * @mbggenerated
     */
    public void setRegionId(Long regionId) {
        this.regionId = regionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ds_t.remark
     *
     * @return the value of ds_t.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ds_t.remark
     *
     * @param remark the value for ds_t.remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ds_t.data_status
     *
     * @return the value of ds_t.data_status
     *
     * @mbggenerated
     */
    public String getDataStatus() {
        return dataStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ds_t.data_status
     *
     * @param dataStatus the value for ds_t.data_status
     *
     * @mbggenerated
     */
    public void setDataStatus(String dataStatus) {
        this.dataStatus = dataStatus == null ? null : dataStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ds_t.create_time
     *
     * @return the value of ds_t.create_time
     *
     * @mbggenerated
     */
    public LocalDate getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ds_t.create_time
     *
     * @param createTime the value for ds_t.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(LocalDate createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ds_t.creator_name
     *
     * @return the value of ds_t.creator_name
     *
     * @mbggenerated
     */
    public String getCreatorName() {
        return creatorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ds_t.creator_name
     *
     * @param creatorName the value for ds_t.creator_name
     *
     * @mbggenerated
     */
    public void setCreatorName(String creatorName) {
        this.creatorName = creatorName == null ? null : creatorName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ds_t.creator
     *
     * @return the value of ds_t.creator
     *
     * @mbggenerated
     */
    public Long getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ds_t.creator
     *
     * @param creator the value for ds_t.creator
     *
     * @mbggenerated
     */
    public void setCreator(Long creator) {
        this.creator = creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ds_t.modify_time
     *
     * @return the value of ds_t.modify_time
     *
     * @mbggenerated
     */
    public LocalDate getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ds_t.modify_time
     *
     * @param modifyTime the value for ds_t.modify_time
     *
     * @mbggenerated
     */
    public void setModifyTime(LocalDate modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ds_t.modifier_name
     *
     * @return the value of ds_t.modifier_name
     *
     * @mbggenerated
     */
    public String getModifierName() {
        return modifierName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ds_t.modifier_name
     *
     * @param modifierName the value for ds_t.modifier_name
     *
     * @mbggenerated
     */
    public void setModifierName(String modifierName) {
        this.modifierName = modifierName == null ? null : modifierName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ds_t.modifier
     *
     * @return the value of ds_t.modifier
     *
     * @mbggenerated
     */
    public Integer getModifier() {
        return modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ds_t.modifier
     *
     * @param modifier the value for ds_t.modifier
     *
     * @mbggenerated
     */
    public void setModifier(Integer modifier) {
        this.modifier = modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ds_t.t
     *
     * @return the value of ds_t.t
     *
     * @mbggenerated
     */
    public BigDecimal getT() {
        return t;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ds_t.t
     *
     * @param t the value for ds_t.t
     *
     * @mbggenerated
     */
    public void setT(BigDecimal t) {
        this.t = t;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ds_t.t_max
     *
     * @return the value of ds_t.t_max
     *
     * @mbggenerated
     */
    public BigDecimal gettMax() {
        return tMax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ds_t.t_max
     *
     * @param tMax the value for ds_t.t_max
     *
     * @mbggenerated
     */
    public void settMax(BigDecimal tMax) {
        this.tMax = tMax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ds_t.t_min
     *
     * @return the value of ds_t.t_min
     *
     * @mbggenerated
     */
    public BigDecimal gettMin() {
        return tMin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ds_t.t_min
     *
     * @param tMin the value for ds_t.t_min
     *
     * @mbggenerated
     */
    public void settMin(BigDecimal tMin) {
        this.tMin = tMin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ds_t.t_stddev
     *
     * @return the value of ds_t.t_stddev
     *
     * @mbggenerated
     */
    public BigDecimal gettStddev() {
        return tStddev;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ds_t.t_stddev
     *
     * @param tStddev the value for ds_t.t_stddev
     *
     * @mbggenerated
     */
    public void settStddev(BigDecimal tStddev) {
        this.tStddev = tStddev;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ds_t.data_time
     *
     * @return the value of ds_t.data_time
     *
     * @mbggenerated
     */
    public LocalDate getDataTime() {
        return dataTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ds_t.data_time
     *
     * @param dataTime the value for ds_t.data_time
     *
     * @mbggenerated
     */
    public void setDataTime(LocalDate dataTime) {
        this.dataTime = dataTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ds_t.publish_status
     *
     * @return the value of ds_t.publish_status
     *
     * @mbggenerated
     */
    public Integer getPublishStatus() {
        return publishStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ds_t.publish_status
     *
     * @param publishStatus the value for ds_t.publish_status
     *
     * @mbggenerated
     */
    public void setPublishStatus(Integer publishStatus) {
        this.publishStatus = publishStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ds_t.publish_time
     *
     * @return the value of ds_t.publish_time
     *
     * @mbggenerated
     */
    public LocalDateTime getPublishTime() {
        return publishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ds_t.publish_time
     *
     * @param publishTime the value for ds_t.publish_time
     *
     * @mbggenerated
     */
    public void setPublishTime(LocalDateTime publishTime) {
        this.publishTime = publishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ds_t.publisher_name
     *
     * @return the value of ds_t.publisher_name
     *
     * @mbggenerated
     */
    public String getPublisherName() {
        return publisherName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ds_t.publisher_name
     *
     * @param publisherName the value for ds_t.publisher_name
     *
     * @mbggenerated
     */
    public void setPublisherName(String publisherName) {
        this.publisherName = publisherName == null ? null : publisherName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ds_t.del_flag
     *
     * @return the value of ds_t.del_flag
     *
     * @mbggenerated
     */
    public String getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ds_t.del_flag
     *
     * @param delFlag the value for ds_t.del_flag
     *
     * @mbggenerated
     */
    public void setDelFlag(String delFlag) {
        this.delFlag = delFlag == null ? null : delFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ds_t.publisher
     *
     * @return the value of ds_t.publisher
     *
     * @mbggenerated
     */
    public Integer getPublisher() {
        return publisher;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ds_t.publisher
     *
     * @param publisher the value for ds_t.publisher
     *
     * @mbggenerated
     */
    public void setPublisher(Integer publisher) {
        this.publisher = publisher;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ds_t.data_type
     *
     * @return the value of ds_t.data_type
     *
     * @mbggenerated
     */
    public Integer getDataType() {
        return dataType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ds_t.data_type
     *
     * @param dataType the value for ds_t.data_type
     *
     * @mbggenerated
     */
    public void setDataType(Integer dataType) {
        this.dataType = dataType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ds_t.resolution
     *
     * @return the value of ds_t.resolution
     *
     * @mbggenerated
     */
    public Integer getResolution() {
        return resolution;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ds_t.resolution
     *
     * @param resolution the value for ds_t.resolution
     *
     * @mbggenerated
     */
    public void setResolution(Integer resolution) {
        this.resolution = resolution;
    }


    public String getResolutionValue() {
        return resolutionValue;
    }

    public void setResolutionValue(String resolutionValue) {
        this.resolutionValue = resolutionValue;
    }

    public String getPublishStatusName() {
        return publishStatusName;
    }

    public void setPublishStatusName(String publishStatusName) {
        this.publishStatusName = publishStatusName;
    }

    public String getRegionName() {
        return regionName;
    }

    public void setRegionName(String regionName) {
        this.regionName = regionName;
    }

    public String getRegionCode() {
        return regionCode;
    }

    public void setRegionCode(String regionCode) {
        this.regionCode = regionCode;
    }
}