package com.jh.data.entity;

import com.fasterxml.jackson.annotation.JsonFormat;
import io.swagger.annotations.ApiModelProperty;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalDateTime;

public class DsTrmm {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ds_trmm.id
     *
     * @mbggenerated
     */
    private Integer id;//主键id

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ds_trmm.region_id
     *
     * @mbggenerated
     */
    private Long regionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ds_trmm.remark
     *
     * @mbggenerated
     */
    private String remark;//备注

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ds_trmm.data_status
     *
     * @mbggenerated
     */
    private String dataStatus;//是否有效

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ds_trmm.create_time
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "创建时间")
    @JsonFormat(pattern = "yyyy-MM-dd")
    private LocalDate createTime;//创建时间

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ds_trmm.creator_name
     *
     * @mbggenerated
     */
    private String creatorName;//创建人名称

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ds_trmm.creator
     *
     * @mbggenerated
     */
    private Long creator;//创建人

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ds_trmm.modify_time
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "更新时间")
    @JsonFormat(pattern = "yyyy-MM-dd")
    private LocalDate modifyTime;//更新时间

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ds_trmm.modifier_name
     *
     * @mbggenerated
     */
    private String modifierName;//更新操作人名称

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ds_trmm.modifier
     *
     * @mbggenerated
     */
    private Integer modifier;//更新操作人

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ds_trmm.trmm
     *
     * @mbggenerated
     */
    private BigDecimal trmm;//区域降雨量1km

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ds_trmm.trmm_max
     *
     * @mbggenerated
     */
    private BigDecimal trmmMax;//区域降雨量最大值1km

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ds_trmm.trmm_min
     *
     * @mbggenerated
     */
    private BigDecimal trmmMin;//区域降雨量最小值1km

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ds_trmm.trmm_stddev
     *
     * @mbggenerated
     */
    private BigDecimal trmmStddev;//区域降雨量标准差1km

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ds_trmm.data_time
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "数据时间")
    @JsonFormat(pattern = "yyyy-MM-dd")
    private LocalDate dataTime;//数据时间

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ds_trmm.publish_status
     *
     * @mbggenerated
     */
    private Integer publishStatus;//发布状态

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ds_trmm.publish_time
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "发布时间")
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private LocalDateTime publishTime;//发布时间

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ds_trmm.publisher_name
     *
     * @mbggenerated
     */
    private String publisherName;//发布人名称

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ds_trmm.del_flag
     *
     * @mbggenerated
     */
    private String delFlag;//删除标识

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ds_trmm.publisher
     *
     * @mbggenerated
     */
    private Integer publisher;//发布人

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ds_trmm.data_type
     *
     * @mbggenerated
     */
    private Integer dataType;//数据类型

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ds_trmm.resolution
     *
     * @mbggenerated
     */
    private Integer resolution;//精度

    private String regionName;//区域中文名

    private String regionCode;//区域Code

    private  String resolutionValue;//精度值


    private String publishStatusName;//发布状态

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ds_trmm.id
     *
     * @return the value of ds_trmm.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ds_trmm.id
     *
     * @param id the value for ds_trmm.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ds_trmm.region_id
     *
     * @return the value of ds_trmm.region_id
     *
     * @mbggenerated
     */
    public Long getRegionId() {
        return regionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ds_trmm.region_id
     *
     * @param regionId the value for ds_trmm.region_id
     *
     * @mbggenerated
     */
    public void setRegionId(Long regionId) {
        this.regionId = regionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ds_trmm.remark
     *
     * @return the value of ds_trmm.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ds_trmm.remark
     *
     * @param remark the value for ds_trmm.remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ds_trmm.data_status
     *
     * @return the value of ds_trmm.data_status
     *
     * @mbggenerated
     */
    public String getDataStatus() {
        return dataStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ds_trmm.data_status
     *
     * @param dataStatus the value for ds_trmm.data_status
     *
     * @mbggenerated
     */
    public void setDataStatus(String dataStatus) {
        this.dataStatus = dataStatus == null ? null : dataStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ds_trmm.create_time
     *
     * @return the value of ds_trmm.create_time
     *
     * @mbggenerated
     */
    public LocalDate getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ds_trmm.create_time
     *
     * @param createTime the value for ds_trmm.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(LocalDate createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ds_trmm.creator_name
     *
     * @return the value of ds_trmm.creator_name
     *
     * @mbggenerated
     */
    public String getCreatorName() {
        return creatorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ds_trmm.creator_name
     *
     * @param creatorName the value for ds_trmm.creator_name
     *
     * @mbggenerated
     */
    public void setCreatorName(String creatorName) {
        this.creatorName = creatorName == null ? null : creatorName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ds_trmm.creator
     *
     * @return the value of ds_trmm.creator
     *
     * @mbggenerated
     */
    public Long getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ds_trmm.creator
     *
     * @param creator the value for ds_trmm.creator
     *
     * @mbggenerated
     */
    public void setCreator(Long creator) {
        this.creator = creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ds_trmm.modify_time
     *
     * @return the value of ds_trmm.modify_time
     *
     * @mbggenerated
     */
    public LocalDate getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ds_trmm.modify_time
     *
     * @param modifyTime the value for ds_trmm.modify_time
     *
     * @mbggenerated
     */
    public void setModifyTime(LocalDate modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ds_trmm.modifier_name
     *
     * @return the value of ds_trmm.modifier_name
     *
     * @mbggenerated
     */
    public String getModifierName() {
        return modifierName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ds_trmm.modifier_name
     *
     * @param modifierName the value for ds_trmm.modifier_name
     *
     * @mbggenerated
     */
    public void setModifierName(String modifierName) {
        this.modifierName = modifierName == null ? null : modifierName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ds_trmm.modifier
     *
     * @return the value of ds_trmm.modifier
     *
     * @mbggenerated
     */
    public Integer getModifier() {
        return modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ds_trmm.modifier
     *
     * @param modifier the value for ds_trmm.modifier
     *
     * @mbggenerated
     */
    public void setModifier(Integer modifier) {
        this.modifier = modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ds_trmm.trmm
     *
     * @return the value of ds_trmm.trmm
     *
     * @mbggenerated
     */
    public BigDecimal getTrmm() {
        return trmm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ds_trmm.trmm
     *
     * @param trmm the value for ds_trmm.trmm
     *
     * @mbggenerated
     */
    public void setTrmm(BigDecimal trmm) {
        this.trmm = trmm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ds_trmm.trmm_max
     *
     * @return the value of ds_trmm.trmm_max
     *
     * @mbggenerated
     */
    public BigDecimal getTrmmMax() {
        return trmmMax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ds_trmm.trmm_max
     *
     * @param trmmMax the value for ds_trmm.trmm_max
     *
     * @mbggenerated
     */
    public void setTrmmMax(BigDecimal trmmMax) {
        this.trmmMax = trmmMax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ds_trmm.trmm_min
     *
     * @return the value of ds_trmm.trmm_min
     *
     * @mbggenerated
     */
    public BigDecimal getTrmmMin() {
        return trmmMin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ds_trmm.trmm_min
     *
     * @param trmmMin the value for ds_trmm.trmm_min
     *
     * @mbggenerated
     */
    public void setTrmmMin(BigDecimal trmmMin) {
        this.trmmMin = trmmMin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ds_trmm.trmm_stddev
     *
     * @return the value of ds_trmm.trmm_stddev
     *
     * @mbggenerated
     */
    public BigDecimal getTrmmStddev() {
        return trmmStddev;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ds_trmm.trmm_stddev
     *
     * @param trmmStddev the value for ds_trmm.trmm_stddev
     *
     * @mbggenerated
     */
    public void setTrmmStddev(BigDecimal trmmStddev) {
        this.trmmStddev = trmmStddev;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ds_trmm.data_time
     *
     * @return the value of ds_trmm.data_time
     *
     * @mbggenerated
     */
    public LocalDate getDataTime() {
        return dataTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ds_trmm.data_time
     *
     * @param dataTime the value for ds_trmm.data_time
     *
     * @mbggenerated
     */
    public void setDataTime(LocalDate dataTime) {
        this.dataTime = dataTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ds_trmm.publish_status
     *
     * @return the value of ds_trmm.publish_status
     *
     * @mbggenerated
     */
    public Integer getPublishStatus() {
        return publishStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ds_trmm.publish_status
     *
     * @param publishStatus the value for ds_trmm.publish_status
     *
     * @mbggenerated
     */
    public void setPublishStatus(Integer publishStatus) {
        this.publishStatus = publishStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ds_trmm.publish_time
     *
     * @return the value of ds_trmm.publish_time
     *
     * @mbggenerated
     */
    public LocalDateTime getPublishTime() {
        return publishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ds_trmm.publish_time
     *
     * @param publishTime the value for ds_trmm.publish_time
     *
     * @mbggenerated
     */
    public void setPublishTime(LocalDateTime publishTime) {
        this.publishTime = publishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ds_trmm.publisher_name
     *
     * @return the value of ds_trmm.publisher_name
     *
     * @mbggenerated
     */
    public String getPublisherName() {
        return publisherName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ds_trmm.publisher_name
     *
     * @param publisherName the value for ds_trmm.publisher_name
     *
     * @mbggenerated
     */
    public void setPublisherName(String publisherName) {
        this.publisherName = publisherName == null ? null : publisherName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ds_trmm.del_flag
     *
     * @return the value of ds_trmm.del_flag
     *
     * @mbggenerated
     */
    public String getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ds_trmm.del_flag
     *
     * @param delFlag the value for ds_trmm.del_flag
     *
     * @mbggenerated
     */
    public void setDelFlag(String delFlag) {
        this.delFlag = delFlag == null ? null : delFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ds_trmm.publisher
     *
     * @return the value of ds_trmm.publisher
     *
     * @mbggenerated
     */
    public Integer getPublisher() {
        return publisher;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ds_trmm.publisher
     *
     * @param publisher the value for ds_trmm.publisher
     *
     * @mbggenerated
     */
    public void setPublisher(Integer publisher) {
        this.publisher = publisher;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ds_trmm.data_type
     *
     * @return the value of ds_trmm.data_type
     *
     * @mbggenerated
     */
    public Integer getDataType() {
        return dataType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ds_trmm.data_type
     *
     * @param dataType the value for ds_trmm.data_type
     *
     * @mbggenerated
     */
    public void setDataType(Integer dataType) {
        this.dataType = dataType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ds_trmm.resolution
     *
     * @return the value of ds_trmm.resolution
     *
     * @mbggenerated
     */
    public Integer getResolution() {
        return resolution;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ds_trmm.resolution
     *
     * @param resolution the value for ds_trmm.resolution
     *
     * @mbggenerated
     */
    public void setResolution(Integer resolution) {
        this.resolution = resolution;
    }

    public String getRegionName() {
        return regionName;
    }

    public void setRegionName(String regionName) {
        this.regionName = regionName;
    }

    public String getRegionCode() {
        return regionCode;
    }

    public void setRegionCode(String regionCode) {
        this.regionCode = regionCode;
    }

    public String getResolutionValue() {
        return resolutionValue;
    }

    public void setResolutionValue(String resolutionValue) {
        this.resolutionValue = resolutionValue;
    }

    public String getPublishStatusName() {
        return publishStatusName;
    }

    public void setPublishStatusName(String publishStatusName) {
        this.publishStatusName = publishStatusName;
    }
}