package com.jh.collector.mapping;

import com.jh.collector.entity.CalibrationInfo;
import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Component;

import java.util.List;

@Mapper
@Component
public interface CalibrationInfoMapper {



    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table is_calibration_info
     *
     * @mbggenerated
     */
    int insert(CalibrationInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table is_calibration_info
     *
     * @mbggenerated
     */
    int insertSelective(CalibrationInfo record);

    void updateInfoById(CalibrationInfo calibrationInfo);

    /**
     * 根据条件返回多个地块信息
     * @param calibrationInfo
    * xzg 2019/7/31 14:27
    * @return
    */
    List<CalibrationInfo> selectCalibrationInfoList(CalibrationInfo calibrationInfo);

}