package com.jh.collector.mapping;

import com.jh.collector.entity.Calibrator;
import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Component;

import java.util.List;

@Mapper
@Component
public interface CalibratorMapper {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table is_calibrator
     *
     * @mbggenerated
     */
    int insert(Calibrator record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table is_calibrator
     *
     * @mbggenerated
     */
    int insertSelective(Calibrator record);

    /**
     * @param param
    * xzg 2019/7/30 14:47
    * @return
    */
    List<Calibrator> selectListByParam(Calibrator param);

    int insertCalibratorForTask(List<Calibrator> list);

}