package com.jh.collector.mapping;

import com.jh.collector.entity.CalibrationSubtask;
import com.jh.collector.entity.Task;
import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Component;

import java.util.List;

@Component
@Mapper
public interface CalibrationSubtaskMapper {


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table is_calibration_subtask
     *
     * @mbggenerated
     */
    int insert(CalibrationSubtask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table is_calibration_subtask
     *
     * @mbggenerated
     */
    int insertSelective(CalibrationSubtask record);

    CalibrationSubtask selectSubtaskOne(CalibrationSubtask record);

    /**
     * 根据任务条件查询 返回多个子任务
     * @param task
     * @return
     */
    List<CalibrationSubtask> selectSubtaskList(Task task);

    /**
     * 更新子任务数据
     * @param record
     * @return
     */
    int updateSubtaskByParam(CalibrationSubtask record);

    /**
     * 根据任务条件查询 返回多个子任务
     * @param calibrationSubtask
     * @return
     */
    List<CalibrationSubtask> querySubTaskList(CalibrationSubtask calibrationSubtask);

    /**
     * 根据任务条件查询 返回多个子任务
     * @param calibrationSubtask
     * @return
     */
    List<CalibrationSubtask> queryTaskVillage(CalibrationSubtask calibrationSubtask);


}