package com.jh.collector.mapping;

import com.jh.collector.entity.Image;
import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Component;

import java.util.List;

@Mapper
@Component
public interface ImageMapper {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table is_image
     *
     * @mbggenerated
     */
    int insert(Image record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table is_image
     *
     * @mbggenerated
     */
    int insertSelective(Image record);

    Integer insertImgUrls(List<Image> imageList);

    int updateImages(Image image);

}