package com.jh.collector.mapping;


import com.jh.collector.entity.MassifInfo;
import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Component;

@Component
@Mapper
public interface MassifInfoMapper {


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table is_massif_info
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String bsm);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table is_massif_info
     *
     * @mbggenerated
     */
    int insert(MassifInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table is_massif_info
     *
     * @mbggenerated
     */
    int insertSelective(MassifInfo record);



    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table is_massif_info
     *
     * @mbggenerated
     */
    MassifInfo selectByPrimaryKey(String bsm);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table is_massif_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(MassifInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table is_massif_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(MassifInfo record);
}