package com.jh.collector.mapping;

import com.jh.collector.entity.PolicyInfo;
import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Component;

import java.util.List;
import java.util.Map;

@Component
@Mapper
public interface PolicyInfoMapper {


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table is_policy_info
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer policyNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table is_policy_info
     *
     * @mbggenerated
     */
    int insert(PolicyInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table is_policy_info
     *
     * @mbggenerated
     */
    int insertSelective(PolicyInfo record);


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table is_policy_info
     *
     * @mbggenerated
     */
    PolicyInfo selectByPrimaryKey(Integer policyNo);



    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table is_policy_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(PolicyInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table is_policy_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(PolicyInfo record);

    List<PolicyInfo> selectPolicyInfoList(PolicyInfo record);

    List<PolicyInfo> queryVillageDetail(Map<String,Object> param);

}