package com.jh.collector.mapping;

import com.jh.collector.entity.Task;
import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Component;

import java.util.List;
import java.util.Map;


@Component
@Mapper
public interface TaskMapper {


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ls_task
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer taskId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ls_task
     *
     * @mbggenerated
     */
    int insert(Task record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ls_task
     *
     * @mbggenerated
     */
    int insertSelective(Task record);



    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ls_task
     *
     * @mbggenerated
     */
    Task selectByPrimaryKey(Integer taskId);


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ls_task
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Task record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ls_task
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Task record);
    
    /**
     * 获取当前登录人的所有任务列表
     * param record
    * xzg 2019/7/30 14:39
    * @return
    */
    List<Task> selectTaskListByAccountId(Integer accountId);


    /**
     * @Author：sxj
     * @Date：2019-07-31
     * 根据创建者查找任务列表
     */
    List<Task> selectTaskListbyCreatorName(Map<String,Object> param);

    /**
     * @Author：sxj
     * @Date：2019-07-31
     * 根据区域id查找任务列表
     */
    List<Task> selectTaskListbyRegionId(String regionId);

}