package com.jh.collector.entity;

import java.math.BigDecimal;
import java.util.Date;

public class CalibrationInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column is_calibration_info.bsm
     *
     * @mbggenerated
     */
    private String bsm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column is_calibration_info.policy_no
     *
     * @mbggenerated
     */
    private Integer policyNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column is_calibration_info.data_status
     *
     * @mbggenerated
     */
    private String dataStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column is_calibration_info.del_flag
     *
     * @mbggenerated
     */
    private String delFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column is_calibration_info.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column is_calibration_info.creator_name
     *
     * @mbggenerated
     */
    private String creatorName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column is_calibration_info.creator
     *
     * @mbggenerated
     */
    private Integer creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column is_calibration_info.modify_time
     *
     * @mbggenerated
     */
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column is_calibration_info.modifier_name
     *
     * @mbggenerated
     */
    private String modifierName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column is_calibration_info.modifier
     *
     * @mbggenerated
     */
    private Integer modifier;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column is_calibration_info.remark
     *
     * @mbggenerated
     */
    private String remark;


    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column is_calibration_info.calibrator
     *
     * @mbggenerated
     */
    private String calibrator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column is_calibration_info.calibrate_no
     *
     * @mbggenerated
     */
    private String massifInfoBsm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column is_calibration_info.calibrate_crop
     *
     * @mbggenerated
     */
    private Integer calibrateCrop;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column is_calibration_info.calibrator_area
     *
     * @mbggenerated
     */
    private BigDecimal calibratorArea;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column is_calibration_info.calibrator_bbox
     *
     * @mbggenerated
     */
    private String calibratorBbox;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column is_calibration_info.bsm
     *
     * @return the value of is_calibration_info.bsm
     *
     * @mbggenerated
     */
    public String getBsm() {
        return bsm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column is_calibration_info.bsm
     *
     * @param bsm the value for is_calibration_info.bsm
     *
     * @mbggenerated
     */
    public void setBsm(String bsm) {
        this.bsm = bsm == null ? null : bsm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column is_calibration_info.policy_no
     *
     * @return the value of is_calibration_info.policy_no
     *
     * @mbggenerated
     */
    public Integer getPolicyNo() {
        return policyNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column is_calibration_info.policy_no
     *
     * @param policyNo the value for is_calibration_info.policy_no
     *
     * @mbggenerated
     */
    public void setPolicyNo(Integer policyNo) {
        this.policyNo = policyNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column is_calibration_info.data_status
     *
     * @return the value of is_calibration_info.data_status
     *
     * @mbggenerated
     */
    public String getDataStatus() {
        return dataStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column is_calibration_info.data_status
     *
     * @param dataStatus the value for is_calibration_info.data_status
     *
     * @mbggenerated
     */
    public void setDataStatus(String dataStatus) {
        this.dataStatus = dataStatus == null ? null : dataStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column is_calibration_info.del_flag
     *
     * @return the value of is_calibration_info.del_flag
     *
     * @mbggenerated
     */
    public String getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column is_calibration_info.del_flag
     *
     * @param delFlag the value for is_calibration_info.del_flag
     *
     * @mbggenerated
     */
    public void setDelFlag(String delFlag) {
        this.delFlag = delFlag == null ? null : delFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column is_calibration_info.create_time
     *
     * @return the value of is_calibration_info.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column is_calibration_info.create_time
     *
     * @param createTime the value for is_calibration_info.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column is_calibration_info.creator_name
     *
     * @return the value of is_calibration_info.creator_name
     *
     * @mbggenerated
     */
    public String getCreatorName() {
        return creatorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column is_calibration_info.creator_name
     *
     * @param creatorName the value for is_calibration_info.creator_name
     *
     * @mbggenerated
     */
    public void setCreatorName(String creatorName) {
        this.creatorName = creatorName == null ? null : creatorName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column is_calibration_info.creator
     *
     * @return the value of is_calibration_info.creator
     *
     * @mbggenerated
     */
    public Integer getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column is_calibration_info.creator
     *
     * @param creator the value for is_calibration_info.creator
     *
     * @mbggenerated
     */
    public void setCreator(Integer creator) {
        this.creator = creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column is_calibration_info.modify_time
     *
     * @return the value of is_calibration_info.modify_time
     *
     * @mbggenerated
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column is_calibration_info.modify_time
     *
     * @param modifyTime the value for is_calibration_info.modify_time
     *
     * @mbggenerated
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column is_calibration_info.modifier_name
     *
     * @return the value of is_calibration_info.modifier_name
     *
     * @mbggenerated
     */
    public String getModifierName() {
        return modifierName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column is_calibration_info.modifier_name
     *
     * @param modifierName the value for is_calibration_info.modifier_name
     *
     * @mbggenerated
     */
    public void setModifierName(String modifierName) {
        this.modifierName = modifierName == null ? null : modifierName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column is_calibration_info.modifier
     *
     * @return the value of is_calibration_info.modifier
     *
     * @mbggenerated
     */
    public Integer getModifier() {
        return modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column is_calibration_info.modifier
     *
     * @param modifier the value for is_calibration_info.modifier
     *
     * @mbggenerated
     */
    public void setModifier(Integer modifier) {
        this.modifier = modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column is_calibration_info.remark
     *
     * @return the value of is_calibration_info.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column is_calibration_info.remark
     *
     * @param remark the value for is_calibration_info.remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column is_calibration_info.calibrator
     *
     * @return the value of is_calibration_info.calibrator
     *
     * @mbggenerated
     */
    public String getCalibrator() {
        return calibrator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column is_calibration_info.calibrator
     *
     * @param calibrator the value for is_calibration_info.calibrator
     *
     * @mbggenerated
     */
    public void setCalibrator(String calibrator) {
        this.calibrator = calibrator == null ? null : calibrator.trim();
    }

    public String getMassifInfoBsm() {
        return massifInfoBsm;
    }

    public void setMassifInfoBsm(String massifInfoBsm) {
        this.massifInfoBsm = massifInfoBsm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column is_calibration_info.calibrate_crop
     *
     * @return the value of is_calibration_info.calibrate_crop
     *
     * @mbggenerated
     */
    public Integer getCalibrateCrop() {
        return calibrateCrop;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column is_calibration_info.calibrate_crop
     *
     * @param calibrateCrop the value for is_calibration_info.calibrate_crop
     *
     * @mbggenerated
     */
    public void setCalibrateCrop(Integer calibrateCrop) {
        this.calibrateCrop = calibrateCrop;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column is_calibration_info.calibrator_area
     *
     * @return the value of is_calibration_info.calibrator_area
     *
     * @mbggenerated
     */
    public BigDecimal getCalibratorArea() {
        return calibratorArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column is_calibration_info.calibrator_area
     *
     * @param calibratorArea the value for is_calibration_info.calibrator_area
     *
     * @mbggenerated
     */
    public void setCalibratorArea(BigDecimal calibratorArea) {
        this.calibratorArea = calibratorArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column is_calibration_info.calibrator_bbox
     *
     * @return the value of is_calibration_info.calibrator_bbox
     *
     * @mbggenerated
     */
    public String getCalibratorBbox() {
        return calibratorBbox;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column is_calibration_info.calibrator_bbox
     *
     * @param calibratorBbox the value for is_calibration_info.calibrator_bbox
     *
     * @mbggenerated
     */
    public void setCalibratorBbox(String calibratorBbox) {
        this.calibratorBbox = calibratorBbox == null ? null : calibratorBbox.trim();
    }
}