package com.jh.collector.entity;



import java.util.Date;

public class CalibrationSubtask {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column is_calibration_subtask.img_id
     *
     * @mbggenerated
     */
    private Integer imgId;

    /**行政村
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column is_calibration_subtask.village
     *
     * @mbggenerated
     */
    private Integer village;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column is_calibration_subtask.polic_num
     *
     * @mbggenerated
     */
    private Integer policNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column is_calibration_subtask.polic_num_finish
     *
     * @mbggenerated
     */
    private Integer policNumFinish;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column is_calibration_subtask.start_date
     *
     * @mbggenerated
     */
    private Date startDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column is_calibration_subtask.end_date
     *
     * @mbggenerated
     */
    private Date endDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column is_calibration_subtask.data_package
     *
     * @mbggenerated
     */
    private Integer dataPackage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column is_calibration_subtask.task_status
     *
     * @mbggenerated
     */
    private Integer taskStatus;

    /**定标人
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column is_calibration_subtask.calibrator
     *
     * @mbggenerated
     */
    private String calibrator;
    private Integer calibratorId;

    /**任务状态
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column is_calibration_subtask.data_status
     *
     * @mbggenerated
     */
    private String dataStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column is_calibration_subtask.del_flag
     *
     * @mbggenerated
     */
    private String delFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column is_calibration_subtask.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column is_calibration_subtask.creator_name
     *
     * @mbggenerated
     */
    private String creatorName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column is_calibration_subtask.creator
     *
     * @mbggenerated
     */
    private Integer creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column is_calibration_subtask.modify_time
     *
     * @mbggenerated
     */
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column is_calibration_subtask.modifier_name
     *
     * @mbggenerated
     */
    private String modifierName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column is_calibration_subtask.modifier
     *
     * @mbggenerated
     */
    private Integer modifier;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column is_calibration_subtask.remark
     *
     * @mbggenerated
     */
    private String remark;

    private Integer taskId;

    private Integer subtaskId;

    private Integer subtaskStatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column is_calibration_subtask.img_id
     *
     * @return the value of is_calibration_subtask.img_id
     *
     * @mbggenerated
     */
    public Integer getImgId() {
        return imgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column is_calibration_subtask.img_id
     *
     * @param imgId the value for is_calibration_subtask.img_id
     *
     * @mbggenerated
     */
    public void setImgId(Integer imgId) {
        this.imgId = imgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column is_calibration_subtask.village
     *
     * @return the value of is_calibration_subtask.village
     *
     * @mbggenerated
     */
    public Integer getVillage() {
        return village;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column is_calibration_subtask.village
     *
     * @param village the value for is_calibration_subtask.village
     *
     * @mbggenerated
     */
    public void setVillage(Integer village) {
        this.village = village;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column is_calibration_subtask.polic_num
     *
     * @return the value of is_calibration_subtask.polic_num
     *
     * @mbggenerated
     */
    public Integer getPolicNum() {
        return policNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column is_calibration_subtask.polic_num
     *
     * @param policNum the value for is_calibration_subtask.polic_num
     *
     * @mbggenerated
     */
    public void setPolicNum(Integer policNum) {
        this.policNum = policNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column is_calibration_subtask.polic_num_finish
     *
     * @return the value of is_calibration_subtask.polic_num_finish
     *
     * @mbggenerated
     */
    public Integer getPolicNumFinish() {
        return policNumFinish;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column is_calibration_subtask.polic_num_finish
     *
     * @param policNumFinish the value for is_calibration_subtask.polic_num_finish
     *
     * @mbggenerated
     */
    public void setPolicNumFinish(Integer policNumFinish) {
        this.policNumFinish = policNumFinish;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column is_calibration_subtask.start_date
     *
     * @return the value of is_calibration_subtask.start_date
     *
     * @mbggenerated
     */
    public Date getStartDate() {
        return startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column is_calibration_subtask.start_date
     *
     * @param startDate the value for is_calibration_subtask.start_date
     *
     * @mbggenerated
     */
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column is_calibration_subtask.end_date
     *
     * @return the value of is_calibration_subtask.end_date
     *
     * @mbggenerated
     */
    public Date getEndDate() {
        return endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column is_calibration_subtask.end_date
     *
     * @param endDate the value for is_calibration_subtask.end_date
     *
     * @mbggenerated
     */
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column is_calibration_subtask.data_package
     *
     * @return the value of is_calibration_subtask.data_package
     *
     * @mbggenerated
     */
    public Integer getDataPackage() {
        return dataPackage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column is_calibration_subtask.data_package
     *
     * @param dataPackage the value for is_calibration_subtask.data_package
     *
     * @mbggenerated
     */
    public void setDataPackage(Integer dataPackage) {
        this.dataPackage = dataPackage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column is_calibration_subtask.task_status
     *
     * @return the value of is_calibration_subtask.task_status
     *
     * @mbggenerated
     */
    public Integer getTaskStatus() {
        return taskStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column is_calibration_subtask.task_status
     *
     * @param taskStatus the value for is_calibration_subtask.task_status
     *
     * @mbggenerated
     */
    public void setTaskStatus(Integer taskStatus) {
        this.taskStatus = taskStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column is_calibration_subtask.calibrator
     *
     * @return the value of is_calibration_subtask.calibrator
     *
     * @mbggenerated
     */
    public String getCalibrator() {
        return calibrator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column is_calibration_subtask.calibrator
     *
     * @param calibrator the value for is_calibration_subtask.calibrator
     *
     * @mbggenerated
     */
    public void setCalibrator(String calibrator) {
        this.calibrator = calibrator == null ? null : calibrator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column is_calibration_subtask.data_status
     *
     * @return the value of is_calibration_subtask.data_status
     *
     * @mbggenerated
     */
    public String getDataStatus() {
        return dataStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column is_calibration_subtask.data_status
     *
     * @param dataStatus the value for is_calibration_subtask.data_status
     *
     * @mbggenerated
     */
    public void setDataStatus(String dataStatus) {
        this.dataStatus = dataStatus == null ? null : dataStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column is_calibration_subtask.del_flag
     *
     * @return the value of is_calibration_subtask.del_flag
     *
     * @mbggenerated
     */
    public String getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column is_calibration_subtask.del_flag
     *
     * @param delFlag the value for is_calibration_subtask.del_flag
     *
     * @mbggenerated
     */
    public void setDelFlag(String delFlag) {
        this.delFlag = delFlag == null ? null : delFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column is_calibration_subtask.create_time
     *
     * @return the value of is_calibration_subtask.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column is_calibration_subtask.create_time
     *
     * @param createTime the value for is_calibration_subtask.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column is_calibration_subtask.creator_name
     *
     * @return the value of is_calibration_subtask.creator_name
     *
     * @mbggenerated
     */
    public String getCreatorName() {
        return creatorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column is_calibration_subtask.creator_name
     *
     * @param creatorName the value for is_calibration_subtask.creator_name
     *
     * @mbggenerated
     */
    public void setCreatorName(String creatorName) {
        this.creatorName = creatorName == null ? null : creatorName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column is_calibration_subtask.creator
     *
     * @return the value of is_calibration_subtask.creator
     *
     * @mbggenerated
     */
    public Integer getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column is_calibration_subtask.creator
     *
     * @param creator the value for is_calibration_subtask.creator
     *
     * @mbggenerated
     */
    public void setCreator(Integer creator) {
        this.creator = creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column is_calibration_subtask.modify_time
     *
     * @return the value of is_calibration_subtask.modify_time
     *
     * @mbggenerated
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column is_calibration_subtask.modify_time
     *
     * @param modifyTime the value for is_calibration_subtask.modify_time
     *
     * @mbggenerated
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column is_calibration_subtask.modifier_name
     *
     * @return the value of is_calibration_subtask.modifier_name
     *
     * @mbggenerated
     */
    public String getModifierName() {
        return modifierName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column is_calibration_subtask.modifier_name
     *
     * @param modifierName the value for is_calibration_subtask.modifier_name
     *
     * @mbggenerated
     */
    public void setModifierName(String modifierName) {
        this.modifierName = modifierName == null ? null : modifierName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column is_calibration_subtask.modifier
     *
     * @return the value of is_calibration_subtask.modifier
     *
     * @mbggenerated
     */
    public Integer getModifier() {
        return modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column is_calibration_subtask.modifier
     *
     * @param modifier the value for is_calibration_subtask.modifier
     *
     * @mbggenerated
     */
    public void setModifier(Integer modifier) {
        this.modifier = modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column is_calibration_subtask.remark
     *
     * @return the value of is_calibration_subtask.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column is_calibration_subtask.remark
     *
     * @param remark the value for is_calibration_subtask.remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    public Integer getTaskId() {
        return taskId;
    }

    public void setTaskId(Integer taskId) {
        this.taskId = taskId;
    }

    public Integer getSubtaskId() {
        return subtaskId;
    }

    public void setSubtaskId(Integer subtaskId) {
        this.subtaskId = subtaskId;
    }


    public Integer getCalibratorId() {
        return calibratorId;
    }

    public void setCalibratorId(Integer calibratorId) {
        this.calibratorId = calibratorId;
    }

    public Integer getSubtaskStatus() {
        return subtaskStatus;
    }

    public void setSubtaskStatus(Integer subtaskStatus) {
        this.subtaskStatus = subtaskStatus;
    }
}