package com.jh.collector.entity;

public class Image {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column is_image.img_id
     *
     * @mbggenerated
     */
    private Integer imgId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column is_image.img_url
     *
     * @mbggenerated
     */
    private String imgUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column is_image.massif_id
     *
     * @mbggenerated
     */
    private String calibrationInfoBsm;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column is_image.img_id
     *
     * @return the value of is_image.img_id
     *
     * @mbggenerated
     */
    public Integer getImgId() {
        return imgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column is_image.img_id
     *
     * @param imgId the value for is_image.img_id
     *
     * @mbggenerated
     */
    public void setImgId(Integer imgId) {
        this.imgId = imgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column is_image.img_url
     *
     * @return the value of is_image.img_url
     *
     * @mbggenerated
     */
    public String getImgUrl() {
        return imgUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column is_image.img_url
     *
     * @param imgUrl the value for is_image.img_url
     *
     * @mbggenerated
     */
    public void setImgUrl(String imgUrl) {
        this.imgUrl = imgUrl == null ? null : imgUrl.trim();
    }

    public String getCalibrationInfoBsm() {
        return calibrationInfoBsm;
    }

    public void setCalibrationInfoBsm(String calibrationInfoBsm) {
        this.calibrationInfoBsm = calibrationInfoBsm;
    }
}