package com.jh.collector.entity;



import java.util.Date;

public class MassifInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column is_massif_info.bsm
     *
     * @mbggenerated
     */
    private String bsm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column is_massif_info.data_status
     *
     * @mbggenerated
     */
    private String dataStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column is_massif_info.del_flag
     *
     * @mbggenerated
     */
    private String delFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column is_massif_info.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column is_massif_info.creator_name
     *
     * @mbggenerated
     */
    private String creatorName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column is_massif_info.creator
     *
     * @mbggenerated
     */
    private Integer creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column is_massif_info.modify_time
     *
     * @mbggenerated
     */
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column is_massif_info.modifier_name
     *
     * @mbggenerated
     */
    private String modifierName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column is_massif_info.modifier
     *
     * @mbggenerated
     */
    private Integer modifier;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column is_massif_info.remark
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column is_massif_info.ysdm
     *
     * @mbggenerated
     */
    private String ysdm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column is_massif_info.dkbm
     *
     * @mbggenerated
     */
    private String dkbm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column is_massif_info.dkmc
     *
     * @mbggenerated
     */
    private String dkmc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column is_massif_info.syqxz
     *
     * @mbggenerated
     */
    private String syqxz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column is_massif_info.dklb
     *
     * @mbggenerated
     */
    private String dklb;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column is_massif_info.tdlylx
     *
     * @mbggenerated
     */
    private String tdlylx;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column is_massif_info.dldj
     *
     * @mbggenerated
     */
    private String dldj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column is_massif_info.tdyt
     *
     * @mbggenerated
     */
    private String tdyt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column is_massif_info.sfjbnt
     *
     * @mbggenerated
     */
    private String sfjbnt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column is_massif_info.dkdz
     *
     * @mbggenerated
     */
    private String dkdz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column is_massif_info.dkxz
     *
     * @mbggenerated
     */
    private String dkxz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column is_massif_info.dknz
     *
     * @mbggenerated
     */
    private String dknz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column is_massif_info.dkbz
     *
     * @mbggenerated
     */
    private String dkbz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column is_massif_info.dkbzxx
     *
     * @mbggenerated
     */
    private String dkbzxx;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column is_massif_info.zjrxm
     *
     * @mbggenerated
     */
    private String zjrxm;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column is_massif_info.bsm
     *
     * @return the value of is_massif_info.bsm
     *
     * @mbggenerated
     */
    public String getBsm() {
        return bsm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column is_massif_info.bsm
     *
     * @param bsm the value for is_massif_info.bsm
     *
     * @mbggenerated
     */
    public void setBsm(String bsm) {
        this.bsm = bsm == null ? null : bsm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column is_massif_info.data_status
     *
     * @return the value of is_massif_info.data_status
     *
     * @mbggenerated
     */
    public String getDataStatus() {
        return dataStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column is_massif_info.data_status
     *
     * @param dataStatus the value for is_massif_info.data_status
     *
     * @mbggenerated
     */
    public void setDataStatus(String dataStatus) {
        this.dataStatus = dataStatus == null ? null : dataStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column is_massif_info.del_flag
     *
     * @return the value of is_massif_info.del_flag
     *
     * @mbggenerated
     */
    public String getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column is_massif_info.del_flag
     *
     * @param delFlag the value for is_massif_info.del_flag
     *
     * @mbggenerated
     */
    public void setDelFlag(String delFlag) {
        this.delFlag = delFlag == null ? null : delFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column is_massif_info.create_time
     *
     * @return the value of is_massif_info.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column is_massif_info.create_time
     *
     * @param createTime the value for is_massif_info.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column is_massif_info.creator_name
     *
     * @return the value of is_massif_info.creator_name
     *
     * @mbggenerated
     */
    public String getCreatorName() {
        return creatorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column is_massif_info.creator_name
     *
     * @param creatorName the value for is_massif_info.creator_name
     *
     * @mbggenerated
     */
    public void setCreatorName(String creatorName) {
        this.creatorName = creatorName == null ? null : creatorName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column is_massif_info.creator
     *
     * @return the value of is_massif_info.creator
     *
     * @mbggenerated
     */
    public Integer getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column is_massif_info.creator
     *
     * @param creator the value for is_massif_info.creator
     *
     * @mbggenerated
     */
    public void setCreator(Integer creator) {
        this.creator = creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column is_massif_info.modify_time
     *
     * @return the value of is_massif_info.modify_time
     *
     * @mbggenerated
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column is_massif_info.modify_time
     *
     * @param modifyTime the value for is_massif_info.modify_time
     *
     * @mbggenerated
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column is_massif_info.modifier_name
     *
     * @return the value of is_massif_info.modifier_name
     *
     * @mbggenerated
     */
    public String getModifierName() {
        return modifierName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column is_massif_info.modifier_name
     *
     * @param modifierName the value for is_massif_info.modifier_name
     *
     * @mbggenerated
     */
    public void setModifierName(String modifierName) {
        this.modifierName = modifierName == null ? null : modifierName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column is_massif_info.modifier
     *
     * @return the value of is_massif_info.modifier
     *
     * @mbggenerated
     */
    public Integer getModifier() {
        return modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column is_massif_info.modifier
     *
     * @param modifier the value for is_massif_info.modifier
     *
     * @mbggenerated
     */
    public void setModifier(Integer modifier) {
        this.modifier = modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column is_massif_info.remark
     *
     * @return the value of is_massif_info.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column is_massif_info.remark
     *
     * @param remark the value for is_massif_info.remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column is_massif_info.ysdm
     *
     * @return the value of is_massif_info.ysdm
     *
     * @mbggenerated
     */
    public String getYsdm() {
        return ysdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column is_massif_info.ysdm
     *
     * @param ysdm the value for is_massif_info.ysdm
     *
     * @mbggenerated
     */
    public void setYsdm(String ysdm) {
        this.ysdm = ysdm == null ? null : ysdm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column is_massif_info.dkbm
     *
     * @return the value of is_massif_info.dkbm
     *
     * @mbggenerated
     */
    public String getDkbm() {
        return dkbm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column is_massif_info.dkbm
     *
     * @param dkbm the value for is_massif_info.dkbm
     *
     * @mbggenerated
     */
    public void setDkbm(String dkbm) {
        this.dkbm = dkbm == null ? null : dkbm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column is_massif_info.dkmc
     *
     * @return the value of is_massif_info.dkmc
     *
     * @mbggenerated
     */
    public String getDkmc() {
        return dkmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column is_massif_info.dkmc
     *
     * @param dkmc the value for is_massif_info.dkmc
     *
     * @mbggenerated
     */
    public void setDkmc(String dkmc) {
        this.dkmc = dkmc == null ? null : dkmc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column is_massif_info.syqxz
     *
     * @return the value of is_massif_info.syqxz
     *
     * @mbggenerated
     */
    public String getSyqxz() {
        return syqxz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column is_massif_info.syqxz
     *
     * @param syqxz the value for is_massif_info.syqxz
     *
     * @mbggenerated
     */
    public void setSyqxz(String syqxz) {
        this.syqxz = syqxz == null ? null : syqxz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column is_massif_info.dklb
     *
     * @return the value of is_massif_info.dklb
     *
     * @mbggenerated
     */
    public String getDklb() {
        return dklb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column is_massif_info.dklb
     *
     * @param dklb the value for is_massif_info.dklb
     *
     * @mbggenerated
     */
    public void setDklb(String dklb) {
        this.dklb = dklb == null ? null : dklb.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column is_massif_info.tdlylx
     *
     * @return the value of is_massif_info.tdlylx
     *
     * @mbggenerated
     */
    public String getTdlylx() {
        return tdlylx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column is_massif_info.tdlylx
     *
     * @param tdlylx the value for is_massif_info.tdlylx
     *
     * @mbggenerated
     */
    public void setTdlylx(String tdlylx) {
        this.tdlylx = tdlylx == null ? null : tdlylx.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column is_massif_info.dldj
     *
     * @return the value of is_massif_info.dldj
     *
     * @mbggenerated
     */
    public String getDldj() {
        return dldj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column is_massif_info.dldj
     *
     * @param dldj the value for is_massif_info.dldj
     *
     * @mbggenerated
     */
    public void setDldj(String dldj) {
        this.dldj = dldj == null ? null : dldj.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column is_massif_info.tdyt
     *
     * @return the value of is_massif_info.tdyt
     *
     * @mbggenerated
     */
    public String getTdyt() {
        return tdyt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column is_massif_info.tdyt
     *
     * @param tdyt the value for is_massif_info.tdyt
     *
     * @mbggenerated
     */
    public void setTdyt(String tdyt) {
        this.tdyt = tdyt == null ? null : tdyt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column is_massif_info.sfjbnt
     *
     * @return the value of is_massif_info.sfjbnt
     *
     * @mbggenerated
     */
    public String getSfjbnt() {
        return sfjbnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column is_massif_info.sfjbnt
     *
     * @param sfjbnt the value for is_massif_info.sfjbnt
     *
     * @mbggenerated
     */
    public void setSfjbnt(String sfjbnt) {
        this.sfjbnt = sfjbnt == null ? null : sfjbnt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column is_massif_info.dkdz
     *
     * @return the value of is_massif_info.dkdz
     *
     * @mbggenerated
     */
    public String getDkdz() {
        return dkdz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column is_massif_info.dkdz
     *
     * @param dkdz the value for is_massif_info.dkdz
     *
     * @mbggenerated
     */
    public void setDkdz(String dkdz) {
        this.dkdz = dkdz == null ? null : dkdz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column is_massif_info.dkxz
     *
     * @return the value of is_massif_info.dkxz
     *
     * @mbggenerated
     */
    public String getDkxz() {
        return dkxz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column is_massif_info.dkxz
     *
     * @param dkxz the value for is_massif_info.dkxz
     *
     * @mbggenerated
     */
    public void setDkxz(String dkxz) {
        this.dkxz = dkxz == null ? null : dkxz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column is_massif_info.dknz
     *
     * @return the value of is_massif_info.dknz
     *
     * @mbggenerated
     */
    public String getDknz() {
        return dknz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column is_massif_info.dknz
     *
     * @param dknz the value for is_massif_info.dknz
     *
     * @mbggenerated
     */
    public void setDknz(String dknz) {
        this.dknz = dknz == null ? null : dknz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column is_massif_info.dkbz
     *
     * @return the value of is_massif_info.dkbz
     *
     * @mbggenerated
     */
    public String getDkbz() {
        return dkbz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column is_massif_info.dkbz
     *
     * @param dkbz the value for is_massif_info.dkbz
     *
     * @mbggenerated
     */
    public void setDkbz(String dkbz) {
        this.dkbz = dkbz == null ? null : dkbz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column is_massif_info.dkbzxx
     *
     * @return the value of is_massif_info.dkbzxx
     *
     * @mbggenerated
     */
    public String getDkbzxx() {
        return dkbzxx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column is_massif_info.dkbzxx
     *
     * @param dkbzxx the value for is_massif_info.dkbzxx
     *
     * @mbggenerated
     */
    public void setDkbzxx(String dkbzxx) {
        this.dkbzxx = dkbzxx == null ? null : dkbzxx.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column is_massif_info.zjrxm
     *
     * @return the value of is_massif_info.zjrxm
     *
     * @mbggenerated
     */
    public String getZjrxm() {
        return zjrxm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column is_massif_info.zjrxm
     *
     * @param zjrxm the value for is_massif_info.zjrxm
     *
     * @mbggenerated
     */
    public void setZjrxm(String zjrxm) {
        this.zjrxm = zjrxm == null ? null : zjrxm.trim();
    }
}