package com.jh.collector.entity;



import java.util.Date;
import java.util.List;

public class Task {
    /**任务id
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ls_task.task_id
     *
     * @mbggenerated
     */
    private Integer taskId;

    /**任务状态
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ls_task.data_status
     *
     * @mbggenerated
     */
    private String dataStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ls_task.del_flag
     *
     * @mbggenerated
     */
    private String delFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ls_task.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ls_task.creator_name
     *
     * @mbggenerated
     */
    private String creatorName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ls_task.creator
     *
     * @mbggenerated
     */
    private Integer creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ls_task.modify_time
     *
     * @mbggenerated
     */
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ls_task.modifier_name
     *
     * @mbggenerated
     */
    private String modifierName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ls_task.modifier
     *
     * @mbggenerated
     */
    private Integer modifier;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ls_task.remark
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ls_task.task_name
     *
     * @mbggenerated
     */
    private String taskName;

    /**区域id  行政村
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ls_task.region_id
     *
     * @mbggenerated
     */
    private Long regionId;

    /**总保单数
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ls_task.insurance_policy_num
     *
     * @mbggenerated
     */
    private Integer insurancePolicyNum;

    /**已定标数
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ls_task.calibrated_policy_number
     *
     * @mbggenerated
     */
    private Integer calibratedPolicyNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ls_task.start_time
     *
     * @mbggenerated
     */
    private Date startTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ls_task.end_time
     *
     * @mbggenerated
     */
    private Date endTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ls_task.status_status
     *
     * @mbggenerated
     */
    private String statusStatus;

    private List<Calibrator> calibrators;

    public List<Calibrator> getCalibrators() {
        return calibrators;
    }

    public void setCalibrators(List<Calibrator> calibrators) {
        this.calibrators = calibrators;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ls_task.task_id
     *
     * @return the value of ls_task.task_id
     *
     * @mbggenerated
     */
    public Integer getTaskId() {
        return taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ls_task.task_id
     *
     * @param taskId the value for ls_task.task_id
     *
     * @mbggenerated
     */
    public void setTaskId(Integer taskId) {
        this.taskId = taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ls_task.data_status
     *
     * @return the value of ls_task.data_status
     *
     * @mbggenerated
     */
    public String getDataStatus() {
        return dataStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ls_task.data_status
     *
     * @param dataStatus the value for ls_task.data_status
     *
     * @mbggenerated
     */
    public void setDataStatus(String dataStatus) {
        this.dataStatus = dataStatus == null ? null : dataStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ls_task.del_flag
     *
     * @return the value of ls_task.del_flag
     *
     * @mbggenerated
     */
    public String getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ls_task.del_flag
     *
     * @param delFlag the value for ls_task.del_flag
     *
     * @mbggenerated
     */
    public void setDelFlag(String delFlag) {
        this.delFlag = delFlag == null ? null : delFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ls_task.create_time
     *
     * @return the value of ls_task.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ls_task.create_time
     *
     * @param createTime the value for ls_task.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ls_task.creator_name
     *
     * @return the value of ls_task.creator_name
     *
     * @mbggenerated
     */
    public String getCreatorName() {
        return creatorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ls_task.creator_name
     *
     * @param creatorName the value for ls_task.creator_name
     *
     * @mbggenerated
     */
    public void setCreatorName(String creatorName) {
        this.creatorName = creatorName == null ? null : creatorName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ls_task.creator
     *
     * @return the value of ls_task.creator
     *
     * @mbggenerated
     */
    public Integer getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ls_task.creator
     *
     * @param creator the value for ls_task.creator
     *
     * @mbggenerated
     */
    public void setCreator(Integer creator) {
        this.creator = creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ls_task.modify_time
     *
     * @return the value of ls_task.modify_time
     *
     * @mbggenerated
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ls_task.modify_time
     *
     * @param modifyTime the value for ls_task.modify_time
     *
     * @mbggenerated
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ls_task.modifier_name
     *
     * @return the value of ls_task.modifier_name
     *
     * @mbggenerated
     */
    public String getModifierName() {
        return modifierName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ls_task.modifier_name
     *
     * @param modifierName the value for ls_task.modifier_name
     *
     * @mbggenerated
     */
    public void setModifierName(String modifierName) {
        this.modifierName = modifierName == null ? null : modifierName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ls_task.modifier
     *
     * @return the value of ls_task.modifier
     *
     * @mbggenerated
     */
    public Integer getModifier() {
        return modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ls_task.modifier
     *
     * @param modifier the value for ls_task.modifier
     *
     * @mbggenerated
     */
    public void setModifier(Integer modifier) {
        this.modifier = modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ls_task.remark
     *
     * @return the value of ls_task.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ls_task.remark
     *
     * @param remark the value for ls_task.remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ls_task.task_name
     *
     * @return the value of ls_task.task_name
     *
     * @mbggenerated
     */
    public String getTaskName() {
        return taskName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ls_task.task_name
     *
     * @param taskName the value for ls_task.task_name
     *
     * @mbggenerated
     */
    public void setTaskName(String taskName) {
        this.taskName = taskName == null ? null : taskName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ls_task.region_id
     *
     * @return the value of ls_task.region_id
     *
     * @mbggenerated
     */
    public Long getRegionId() {
        return regionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ls_task.region_id
     *
     * @param regionId the value for ls_task.region_id
     *
     * @mbggenerated
     */
    public void setRegionId(Long regionId) {
        this.regionId = regionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ls_task.insurance_policy_num
     *
     * @return the value of ls_task.insurance_policy_num
     *
     * @mbggenerated
     */
    public Integer getInsurancePolicyNum() {
        return insurancePolicyNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ls_task.insurance_policy_num
     *
     * @param insurancePolicyNum the value for ls_task.insurance_policy_num
     *
     * @mbggenerated
     */
    public void setInsurancePolicyNum(Integer insurancePolicyNum) {
        this.insurancePolicyNum = insurancePolicyNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ls_task.calibrated_policy_number
     *
     * @return the value of ls_task.calibrated_policy_number
     *
     * @mbggenerated
     */
    public Integer getCalibratedPolicyNumber() {
        return calibratedPolicyNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ls_task.calibrated_policy_number
     *
     * @param calibratedPolicyNumber the value for ls_task.calibrated_policy_number
     *
     * @mbggenerated
     */
    public void setCalibratedPolicyNumber(Integer calibratedPolicyNumber) {
        this.calibratedPolicyNumber = calibratedPolicyNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ls_task.start_time
     *
     * @return the value of ls_task.start_time
     *
     * @mbggenerated
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ls_task.start_time
     *
     * @param startTime the value for ls_task.start_time
     *
     * @mbggenerated
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ls_task.end_time
     *
     * @return the value of ls_task.end_time
     *
     * @mbggenerated
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ls_task.end_time
     *
     * @param endTime the value for ls_task.end_time
     *
     * @mbggenerated
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ls_task.status_status
     *
     * @return the value of ls_task.status_status
     *
     * @mbggenerated
     */
    public String getStatusStatus() {
        return statusStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ls_task.status_status
     *
     * @param statusStatus the value for ls_task.status_status
     *
     * @mbggenerated
     */
    public void setStatusStatus(String statusStatus) {
        this.statusStatus = statusStatus == null ? null : statusStatus.trim();
    }
}